.arm
.align 2

// included from "battle_tower_create_party.s"


// fire gold battle tower hard mode spreads

.global PokemonTableStartHardMode
PokemonTableStartHardMode:
.hword 1, 50, venusaur, wiseglasses, energyball, sludgebomb, earthpower, leechseed
.hword 2, 50, venusaur, blacksludge, leechseed, toxic, protect, gigadrain
.hword 3, 50, venusaur, whiteherb, leafstorm, earthquake, outrage, swordsdance
.hword 4, 50, venusaur, heatrock, sunnyday, synthesis, solarbeam, earthpower
.hword 5, 50, charizard, choiceband, flareblitz, thunderpunch, rockslide, aerialace
.hword 6, 50, charizard, salacberry, overheat, earthquake, bellydrum, substitute
.hword 7, 50, charizard, choicespecs, heatwave, dragonpulse, airslash, focusblast
.hword 8, 50, charizard, chartiberry, flamethrower, sunnyday, solarbeam, earthquake
.hword 9, 50, blastoise, expertbelt, waterspout, blizzard, earthquake, flashcannon
.hword 10, 50, blastoise, rindoberry, surf, icebeam, fakeout, earthquake
.hword 11, 50, blastoise, leftovers, toxic, rest, surf, protect
.hword 12, 50, blastoise, sitrusberry, irondefense, bodypress, hydropump, icebeam
.hword 13, 50, pidgeot, choicespecs, hurricane, mudslap, hyperbeam, heatwave
.hword 14, 50, pidgeot, wiseglasses, airslash, heatwave, uturn, hyperbeam
.hword 15, 50, pidgeot, muscleband, bravebird, doubleedge, uturn, whirlwind
.hword 16, 50, pidgeot, wacanberry, featherdance, airslash, roost, mudslap
.hword 17, 50, arbok, sitrusberry, coil, gunkshot, irontail, earthquake
.hword 18, 50, arbok, payapaberry, glare, coil, gunkshot, irontail
.hword 19, 50, arbok, lumberry, glare, poisonjab, crunch, earthquake
.hword 20, 50, arbok, expertbelt, coil, gunkshot, thunderfang, icefang
.hword 21, 50, raichu, brightpowder, fakeout, nuzzle, thunderbolt, attract
.hword 22, 50, raichu, magnet, focusblast, thunder, raindance, nuzzle
.hword 23, 50, raichu, leftovers, encore, voltswitch, charm, faketears
.hword 24, 50, raichu, lifeorb, thunderpunch, irontail, fakeout, brickbreak
.hword 25, 50, sandslash, assaultvest, rapidspin, earthquake, stoneedge, knockoff
.hword 26, 50, sandslash, lumberry, defensecurl, rollout, earthquake, rest
.hword 27, 50, sandslash, brightpowder, sandstorm, earthquake, rockslide, swordsdance
.hword 28, 50, sandslash, choiceband, poisonjab, xscissor, earthquake, rockslide
.hword 29, 50, nidoqueen, weaknesspolicy, toxic, attract, poisonjab, earthquake
.hword 30, 50, nidoqueen, choiceband, earthquake, poisonjab, superpower, crunch
.hword 31, 50, nidoqueen, lifeorb, sludgebomb, earthpower, thunderbolt, shadowball
.hword 32, 50, nidoqueen, lifeorb, earthpower, thunderbolt, flamethrower, icebeam
.hword 33, 50, nidoking, blacksludge, toxic, doubleteam, protect, dig
.hword 34, 50, nidoking, choiceband, earthquake, poisonjab, rockslide, megahorn
.hword 35, 50, nidoking, lifeorb, sludgebomb, earthpower, icebeam, rockslide
.hword 36, 50, nidoking, lifeorb, sludgebomb, thunderbolt, icebeam, flamethrower
.hword 37, 50, clefable, lifeorb, cosmicpower, flamethrower, moonblast, moonlight
.hword 38, 50, clefable, leftovers, calmmind, storedpower, moonblast, moonlight
.hword 39, 50, clefable, lifeorb, moonblast, psychic, flamethrower, thunderbolt
.hword 40, 50, clefable, leftovers, toxic, protect, moonblast, wish
.hword 41, 50, ninetales, leftovers, hypnosis, firespin, protect, flamethrower
.hword 42, 50, ninetales, salacberry, heatwave, nastyplot, solarbeam, darkpulse
.hword 43, 50, ninetales, sitrusberry, willowisp, flamethrower, protect, extrasensory
.hword 44, 50, ninetales, expertbelt, overheat, irontail, solarbeam, foulplay
.hword 45, 50, wigglytuff, widelens, sing, disable, playrough, rest
.hword 46, 50, wigglytuff, choicespecs, hypervoice, dazzlinggleam, psychic, icebeam
.hword 47, 50, wigglytuff, widelens, dazzlinggleam, fireblast, thunder, blizzard
.hword 48, 50, wigglytuff, wiseglasses, dazzlinggleam, flamethrower, thunderbolt, icebeam
.hword 49, 50, vileplume, cobaberry, sunnyday, solarbeam, moonlight, sludgebomb
.hword 50, 50, vileplume, lifeorb, gigadrain, sludgebomb, moonblast, sunnyday
.hword 51, 50, vileplume, blacksludge, teeterdance, moonlight, sludgebomb, gigadrain
.hword 52, 50, vileplume, blacksludge, toxic, gigadrain, protect, moonlight
.hword 53, 50, parasect, leftovers, leechlife, spore, gigadrain, protect
.hword 54, 50, parasect, cobaberry, leechlife, spore, dig, seedbomb
.hword 55, 50, parasect, muscleband, leechlife, spore, crosspoison, seedbomb
.hword 56, 50, parasect, silverpowder, leechlife, spore, screech, bulletseed
.hword 57, 50, venomoth, brightpowder, doubleteam, quiverdance, signalbeam, gigadrain
.hword 58, 50, venomoth, blacksludge, attract, toxic, protect, bugbuzz
.hword 59, 50, venomoth, focussash, quiverdance, bugbuzz, sludgebomb, psychic
.hword 60, 50, venomoth, focussash, quiverdance, bugbuzz, sludgebomb, gigadrain
.hword 61, 50, dugtrio, liechiberry, earthquake, rockslide, nightslash, substitute
.hword 62, 50, dugtrio, focussash, earthquake, reversal, substitute, rockslide
.hword 63, 50, dugtrio, choiceband, earthquake, stoneedge, shadowclaw, aerialace
.hword 64, 50, dugtrio, brightpowder, earthquake, sandstorm, doubleteam, attract
.hword 65, 50, persian, brightpowder, fakeout, attract, frustration, doubleteam
.hword 66, 50, persian, wiseglasses, fakeout, swift, shockwave, waterpulse
.hword 67, 50, persian, silkscarf, fakeout, bite, doubleedge, uturn
.hword 68, 50, persian, choiceband, playrough, doubleedge, irontail, uturn
.hword 69, 50, golduck, sitrusberry, calmmind, encore, scald, icebeam
.hword 70, 50, golduck, expertbelt, honeclaws, hydropump, blizzard, crosschop
.hword 71, 50, golduck, choicespecs, surf, psychic, icebeam, focusblast
.hword 72, 50, golduck, muscleband, waterfall, zenheadbutt, swagger, psychup
.hword 73, 50, annihilape, lifeorb, closecombat, ragefist, uturn, rockslide
.hword 74, 50, annihilape, choiceband, closecombat, ragefist, uturn, stoneedge
.hword 75, 50, annihilape, salacberry, ragefist, endure, reversal, rocktomb
.hword 76, 50, annihilape, leftovers, bulkup, drainpunch, ragefist, earthquake
.hword 77, 50, arcanine, choiceband, flareblitz, closecombat, wildcharge, crunch
.hword 78, 50, arcanine, choiceband, flareblitz, closecombat, playrough, outrage
.hword 79, 50, arcanine, weaknesspolicy, flamethrower, extremespeed, dragonpulse, roar
.hword 80, 50, arcanine, leftovers, willowisp, snarl, flamethrower, morningsun
.hword 81, 50, poliwrath, assaultvest, waterfall, stormthrow, icepunch, earthquake
.hword 82, 50, poliwrath, brightpowder, hypnosis, substitute, focuspunch, doubleteam
.hword 83, 50, poliwrath, widelens, raindance, hydropump, focusblast, blizzard
.hword 84, 50, poliwrath, chestoberry, bulkup, drainpunch, waterfall, rest
.hword 85, 50, alakazam, focussash, calmmind, encore, protect, psychic
.hword 86, 50, alakazam, colburberry, calmmind, recover, psychic, dazzlinggleam
.hword 87, 50, alakazam, lifeorb, psyshock, energyball, shadowball, focusblast
.hword 88, 50, alakazam, lifeorb, calmmind, focusblast, grassknot, psyshock
.hword 89, 50, machamp, assaultvest, dynamicpunch, stoneedge, thunderpunch, bulletpunch
.hword 90, 50, machamp, payapaberry, dynamicpunch, stoneedge, knockoff, bulletpunch
.hword 91, 50, machamp, scopelens, crosschop, stoneedge, focusenergy, knockoff
.hword 92, 50, machamp, flameorb, facade, closecombat, rocktomb, knockoff
.hword 93, 50, victreebel, muscleband, sunnyday, leafblade, poisonjab, suckerpunch
.hword 94, 50, victreebel, expertbelt, sunnyday, solarbeam, sludgebomb, weatherball
.hword 95, 50, victreebel, sitrusberry, swordsdance, leechlife, leafblade, suckerpunch
.hword 96, 50, victreebel, miracleseed, leafstorm, knockoff, leafblade, poisonjab
.hword 97, 50, tentacruel, assaultvest, surf, sludgebomb, mirrorcoat, icebeam
.hword 98, 50, tentacruel, wiseglasses, hydropump, gigadrain, icebeam, sludgebomb
.hword 99, 50, tentacruel, blacksludge, acidspray, gigadrain, toxicspikes, protect
.hword 100, 50, tentacruel, blacksludge, toxic, venoshock, hydropump, gigadrain
.hword 101, 50, golem, quickclaw, doubleedge, earthquake, stoneedge, firepunch
.hword 102, 50, golem, choiceband, doubleedge, earthquake, rockblast, thunderpunch
.hword 103, 50, golem, rockyhelmet, stealthrock, earthquake, roar, protect
.hword 104, 50, golem, choicescarf, earthquake, rockslide, thunderpunch, firepunch
.hword 105, 50, rapidash, choiceband, flareblitz, smartstrike, megahorn, poisonjab
.hword 106, 50, rapidash, widelens, fireblast, horndrill, willowisp, bounce
.hword 107, 50, rapidash, expertbelt, flareblitz, bounce, hihorsepower, megahorn
.hword 108, 50, rapidash, brightpowder, hypnosis, doubleteam, horndrill, flamethrower
.hword 109, 50, slowbro, leftovers, slackoff, scald, psychic, calmmind
.hword 110, 50, slowbro, sitrusberry, trickroom, surf, icebeam, flamethrower
.hword 111, 50, slowbro, lumberry, slackoff, surf, earthquake, toxic
.hword 112, 50, slowbro, sitrusberry, yawn, surf, psychic, trickroom
.hword 113, 50, dodrio, lifeorb, swordsdance, jumpkick, drillpeck, doubleedge
.hword 114, 50, dodrio, focusband, swordsdance, drillrun, bravebird, facade
.hword 115, 50, dodrio, salacberry, endure, flail, drillpeck, swordsdance
.hword 116, 50, dodrio, choiceband, drillrun, jumpkick, bravebird, doubleedge
.hword 117, 50, dewgong, chestoberry, rest, surf, icebeam, signalbeam
.hword 118, 50, dewgong, widelens, sheercold, horndrill, rest, sleeptalk
.hword 119, 50, dewgong, mysticwater, hail, blizzard, aquajet, surf
.hword 120, 50, dewgong, icyrock, hail, dive, toxic, blizzard
.hword 121, 50, muk, muscleband, rocktomb, poisonjab, shadowsneak, explosion
.hword 122, 50, muk, brightpowder, gunkshot, minimize, firepunch, thunderpunch
.hword 123, 50, muk, blacksludge, minimize, poisonjab, toxic, mudbomb
.hword 124, 50, muk, assaultvest, gigadrain, flamethrower, sludgebomb, moonblast
.hword 125, 50, cloyster, leftovers, spikes, dive, toxic, protect
.hword 126, 50, cloyster, leftovers, protect, icebeam, spikes, clamp
.hword 127, 50, cloyster, focussash, shellsmash, hydropump, iciclespear, rockblast
.hword 128, 50, cloyster, focussash, shellsmash, twineedle, iciclespear, rockblast
.hword 129, 50, gengar, focussash, sludgebomb, shadowball, thunderbolt, destinybond
.hword 130, 50, gengar, lifeorb, sludgebomb, focusblast, icywind, shadowball
.hword 131, 50, gengar, sludgebomb, willowisp, shadowball, disable, protect
.hword 132, 50, gengar, payapaberry, sludgebomb, shadowball, nastyplot, explosion
.hword 133, 50, hypno, sitrusberry, swagger, psychup, zenheadbutt, drainpunch
.hword 134, 50, hypno, focusband, trick, thunderpunch, icepunch, zenheadbutt
.hword 135, 50, hypno, sitrusberry, psychic, nastyplot, hypnosis, focusblast
.hword 136, 50, hypno, widelens, hypnosis, dreameater, doubleteam, wakeupslap
.hword 137, 50, kingler, lifeorb, crabhammer, xscissor, nightslash, hammerarm
.hword 138, 50, kingler, lumberry, crabhammer, rockslide, knockoff, agility
.hword 139, 50, kingler, assaultvest, crabhammer, dig, hammerarm, guillotine
.hword 140, 50, kingler, salacberry, crabhammer, swordsdance, flail, endure
.hword 141, 50, electrode, magnet, raindance, thunder, voltswitch, explosion
.hword 142, 50, electrode, shucaberry, foulplay, thunderbolt, signalbeam, thunderwave
.hword 143, 50, electrode, leftovers, chargebeam, doubleteam, toxic, protect
.hword 144, 50, electrode, shucaberry, eerieimpulse, thunderbolt, signalbeam, thunderwave
.hword 145, 50, exeggutor, sitrusberry, sunnyday, solarbeam, psychic, ancientpower
.hword 146, 50, exeggutor, lifeorb, trickroom, energyball, psychic, sleeppowder
.hword 147, 50, exeggutor, sitrusberry, leafstorm, woodhammer, leechseed, zenheadbutt
.hword 148, 50, exeggutor, wiseglasses, sleeppowder, energyball, psychic, synthesis
.hword 149, 50, marowak, thickclub, firepunch, rocktomb, earthquake, doubleedge
.hword 150, 50, marowak, thickclub, thunderpunch, rockslide, earthquake, doubleedge
.hword 151, 50, marowak, thickclub, firepunch, thunderpunch, bonerush, rockslide
.hword 152, 50, marowak, thickclub, earthquake, thunderpunch, stoneedge, ironhead
.hword 153, 50, hitmonlee, assaultvest, closecombat, facade, rockslide, lowsweep
.hword 154, 50, hitmonlee, lifeorb, closecombat, stoneedge, earthquake, blazekick
.hword 155, 50, hitmonlee, salacberry, megakick, highjumpkick, endure, blazekick
.hword 156, 50, hitmonlee, salacberry, reversal, endure, rocktomb, substitute
.hword 157, 50, hitmonchan, expertbelt, firepunch, icepunch, thunderpunch, machpunch
.hword 158, 50, hitmonchan, sitrusberry, drainpunch, counter, machpunch, detect
.hword 159, 50, hitmonchan, blackbelt, closecombat, machpunch, endure, firepunch
.hword 160, 50, hitmonchan, leftovers, substitute, focuspunch, detect, icepunch
.hword 161, 50, weezing, wiseglasses, sludgebomb, thunderbolt, darkpulse, willowisp
.hword 162, 50, weezing, rockyhelmet, willowisp, painsplit, sludgebomb, darkpulse
.hword 163, 50, weezing, choicespecs, thunderbolt, flamethrower, sludgebomb, darkpulse
.hword 164, 50, weezing, sitrusberry, gunkshot, fireblast, explosion, payback
.hword 165, 50, kangaskhan, salacberry, frustration, reversal, endure, crunch
.hword 166, 50, kangaskhan, muscleband, firepunch, icepunch, thunderpunch, megakick
.hword 167, 50, kangaskhan, choiceband, rockslide, hammerarm, shadowclaw, frustration
.hword 168, 50, kangaskhan, assaultvest, earthquake, outrage, crunch, gigaimpact
.hword 169, 50, seaking, rindoberry, waterfall, poisonjab, drillrun, swordsdance
.hword 170, 50, seaking, muscleband, raindance, waterfall, megahorn, drillrun
.hword 171, 50, seaking, chestoberry, haze, horndrill, waterfall, rest
.hword 172, 50, seaking, salacberry, flail, endure, swordsdance, waterfall
.hword 173, 50, starmie, leftovers, cosmicpower, minimize, recover, surf
.hword 174, 50, starmie, expertbelt, surf, psychic, icebeam, recover
.hword 175, 50, starmie, lifeorb, surf, psychic, thunderbolt, dazzlinggleam
.hword 176, 50, starmie, choicespecs, psychic, thunderbolt, icebeam, powergem
.hword 177, 50, jynx, brightpowder, lovelykiss, blizzard, psychic, doubleteam
.hword 178, 50, jynx, lifeorb, lovelykiss, icebeam, psychic, waterpulse
.hword 179, 50, jynx, leftovers, attract, sweetkiss, lovelykiss, icebeam
.hword 180, 50, jynx, nevermeltice, doubleteam, lovelykiss, calmmind, icebeam
.hword 181, 50, pinsir, sitrusberry, xscissor, swordsdance, earthquake, quickattack
.hword 182, 50, pinsir, lifeorb, xscissor, rockslide, earthquake, quickattack
.hword 183, 50, pinsir, choicescarf, xscissor, superpower, rockslide, earthquake
.hword 184, 50, pinsir, muscleband, xscissor, earthquake, superpower, quickattack
.hword 185, 50, tauros, lifeorb, doubleedge, earthquake, blizzard, zenheadbutt
.hword 186, 50, tauros, choiceband, doubleedge, earthquake, rockslide, wildcharge
.hword 187, 50, tauros, focusband, endure, bodyslam, earthquake, zenheadbutt
.hword 188, 50, tauros, expertbelt, blizzard, irontail, earthquake, rockslide
.hword 189, 50, gyarados, wiseglasses, hydropump, thunder, hurricane, raindance
.hword 190, 50, gyarados, choiceband, waterfall, stoneedge, bounce, earthquake
.hword 191, 50, gyarados, lumberry, waterfall, dragondance, icefang, earthquake
.hword 192, 50, gyarados, wacanberry, waterfall, thunderwave, icefang, earthquake
.hword 193, 50, lapras, assaultvest, surf, icebeam, psychic, thunderbolt
.hword 194, 50, lapras, leftovers, freezedry, surf, rest, toxic
.hword 195, 50, lapras, leftovers, rest, sleeptalk, horndrill, fissure
.hword 196, 50, lapras, weaknesspolicy, drillrun, surf, icebeam, iceshard
.hword 197, 50, ditto, choicescarf, transform, 0, 0, 0
.hword 198, 50, ditto, lifeorb, transform, 0, 0, 0
.hword 199, 50, ditto, leftovers, transform, 0, 0, 0
.hword 200, 50, ditto, sitrusberry, transform, 0, 0, 0
.hword 201, 50, vaporeon, leftovers, surf, icebeam, acidarmor, yawn
.hword 202, 50, vaporeon, wacanberry, surf, icebeam, wish, yawn
.hword 203, 50, vaporeon, chestoberry, surf, icebeam, toxic, rest
.hword 204, 50, vaporeon, sitrusberry, surf, icebeam, raindance, yawn
.hword 205, 50, jolteon, magnet, voltswitch, thunder, raindance, shadowball
.hword 206, 50, jolteon, choicespecs, voltswitch, thunderbolt, shadowball, hiddenpower
.hword 207, 50, jolteon, shucaberry, voltswitch, yawn, shadowball, wish
.hword 208, 50, jolteon, choicespecs, voltswitch, signalbeam, shadowball, hiddenpower
.hword 209, 50, flareon, whiteherb, overheat, superpower, willowisp, quickattack
.hword 210, 50, flareon, charcoal, overheat, flareblitz, quickattack, protect
.hword 211, 50, flareon, muscleband, yawn, flareblitz, protect, dig
.hword 212, 50, flareon, choiceband, overheat, flareblitz, irontail, superpower
.hword 213, 50, omastar, focussash, shellsmash, surf, rockslide, icebeam
.hword 214, 50, omastar, lifeorb, raindance, surf, stoneedge, icebeam
.hword 215, 50, omastar, whiteherb, shellsmash, hydropump, ancientpower, earthpower
.hword 216, 50, omastar, muscleband, shellsmash, surf, stoneedge, earthquake
.hword 217, 50, kabutops, rindoberry, swordsdance, liquidation, stoneedge, aquajet
.hword 218, 50, kabutops, focussash, raindance, liquidation, rockslide, earthquake
.hword 219, 50, kabutops, choiceband, knockoff, gigadrain, liquidation, rockslide
.hword 220, 50, kabutops, assaultvest, earthquake, gigadrain, liquidation, stoneedge
.hword 221, 50, aerodactyl, choiceband, rockslide, firefang, thunderfang, icefang
.hword 222, 50, aerodactyl, lifeorb, rockslide, fly, earthquake, thunderfang
.hword 223, 50, aerodactyl, muscleband, stoneedge, earthquake, dragonclaw, fly
.hword 224, 50, aerodactyl, focussash, stoneedge, crunch, ironhead, earthquake
.hword 225, 50, snorlax, figyberry, bellydrum, bodyslam, thunderpunch, earthquake
.hword 226, 50, snorlax, figyberry, curse, recycle, crunch, bodyslam
.hword 227, 50, snorlax, choiceband, selfdestruct, earthquake, thunderpunch, crunch
.hword 228, 50, snorlax, figyberry, curse, recycle, bodyslam, earthquake
.hword 229, 50, articuno, leftovers, icebeam, airslash, substitute, roost
.hword 230, 50, articuno, leftovers, mindreader, sheercold, doubleteam, roost
.hword 231, 50, zapdos, expertbelt, drillpeck, thunderbolt, heatwave, roost
.hword 232, 50, zapdos, sitrusberry, raindance, thunder, hurricane, roost
.hword 233, 50, moltres, brightpowder, overheat, skyattack, doubleteam, roost
.hword 234, 50, moltres, lifeorb, airslash, flamethrower, ancientpower, roost
.hword 235, 50, dragonite, weaknesspolicy, dragondance, outrage, earthquake, thunderpunch
.hword 236, 50, dragonite, lumberry, dragondance, outrage, firepunch, thunderwave
.hword 237, 50, dragonite, weaknesspolicy, dracometeor, firepunch, icepunch, extremespeed
.hword 238, 50, dragonite, leftovers, dragondance, dragonclaw, earthquake, roost
.hword 239, 50, meganium, weaknesspolicy, gigadrain, earthquake, growth, leechseed
.hword 240, 50, meganium, leftovers, gigadrain, protect, toxic, leechseed
.hword 241, 50, meganium, miracleseed, leafstorm, earthquake, synthesis, petalblizzard
.hword 242, 50, meganium, sitrusberry, gigadrain, ancientpower, protect, leechseed
.hword 243, 50, typhlosion, passhoberry, flamethrower, sunnyday, solarbeam, focusblast
.hword 244, 50, typhlosion, lifeorb, flamethrower, thunderpunch, earthquake, extrasensory
.hword 245, 50, typhlosion, leftovers, flamethrower, doubleteam, substitute, willowisp
.hword 246, 50, typhlosion, choicescarf, eruption, focusblast, earthquake, extrasensory
.hword 247, 50, feraligatr, lumberry, waterfall, icepunch, dragondance, earthquake
.hword 248, 50, feraligatr, choiceband, waterfall, icepunch, superpower, crunch
.hword 249, 50, feraligatr, assaultvest, aquatail, earthquake, superpower, crunch
.hword 250, 50, feraligatr, lumberry, aquatail, earthquake, dragondance, crunch
.hword 251, 50, crobat, sitrusberry, acrobatics, crosspoison, gigadrain, uturn
.hword 252, 50, crobat, choiceband, bravebird, crosspoison, heatwave, uturn
.hword 253, 50, crobat, choicespecs, airslash, heatwave, gigadrain, sludgebomb
.hword 254, 50, crobat, blacksludge, toxic, fly, protect, roost
.hword 255, 50, lanturn, leftovers, toxic, dive, rest, protect
.hword 256, 50, lanturn, lumberry, surf, thunderbolt, icebeam, rest
.hword 257, 50, lanturn, damprock, hydropump, thunder, raindance, thunderwave
.hword 258, 50, lanturn, magoberry, thunderwave, surf, icebeam, signalbeam
.hword 259, 50, xatu, assaultvest, psychic, shadowball, heatwave, gigadrain
.hword 260, 50, xatu, leftovers, psyshock, roost, toxic, taunt
.hword 261, 50, xatu, leftovers, psychic, confuseray, thunderwave, airslash
.hword 262, 50, xatu, sitrusberry, storedpower, airslash, calmmind, roost
.hword 263, 50, ampharos, wikiberry, cottonguard, thunderwave, thunderbolt, dragonpulse
.hword 264, 50, ampharos, shucaberry, thunderwave, thunderbolt, powergem, signalbeam
.hword 265, 50, ampharos, magnet, thunderbolt, focusblast, thunderwave, dragonpulse
.hword 266, 50, ampharos, leftovers, thunderbolt, focusblast, thunderwave, confuseray
.hword 267, 50, bellossom, occaberry, quiverdance, sleeppowder, petaldance, moonblast
.hword 268, 50, bellossom, sitrusberry, quiverdance, sunnyday, solarbeam, hiddenpower
.hword 269, 50, bellossom, muscleband, swordsdance, leafblade, drainpunch, moonlight
.hword 270, 50, bellossom, lifeorb, quiverdance, gigadrain, moonblast, sludgebomb
.hword 271, 50, azumarill, assaultvest, waterfall, aquajet, playrough, superpower
.hword 272, 50, azumarill, sitrusberry, waterfall, aquajet, playrough, bellydrum
.hword 273, 50, azumarill, choiceband, waterfall, aquajet, playrough, knockoff
.hword 274, 50, azumarill, assaultvest, aquajet, dig, playrough, knockoff
.hword 275, 50, sudowoodo, assaultvest, headsmash, woodhammer, suckerpunch, hammerarm
.hword 276, 50, sudowoodo, choiceband, headsmash, woodhammer, suckerpunch, earthquake
.hword 277, 50, sudowoodo, choicescarf, headsmash, firepunch, icepunch, earthquake
.hword 278, 50, sudowoodo, choiceband, headsmash, earthquake, suckerpunch, explosion
.hword 279, 50, politoed, choicespecs, surf, icebeam, psychic, focusblast
.hword 280, 50, politoed, leftovers, dive, rest, toxic, bounce
.hword 281, 50, politoed, sitrusberry, bellydrum, waterfall, icepunch, earthquake
.hword 282, 50, politoed, leftovers, scald, icebeam, doubleteam, rest
.hword 283, 50, jumpluff, leftovers, gigadrain, sleeppowder, cottonguard, leechseed
.hword 284, 50, jumpluff, brightpowder, seedbomb, bounce, stunspore, doubleteam
.hword 285, 50, jumpluff, focussash, seedbomb, bounce, swordsdance, sleeppowder
.hword 286, 50, jumpluff, sitrusberry, gigadrain, cottonguard, sleeppowder, leechseed
.hword 287, 50, sunflora, choicespecs, leafstorm, earthpower, hiddenpower, sludgebomb
.hword 288, 50, sunflora, lifeorb, sunnyday, solarbeam, earthpower, synthesis
.hword 289, 50, sunflora, wiseglasses, grasswhistle, energyball, earthpower, sludgebomb
.hword 290, 50, sunflora, choicespecs, leafstorm, hyperbeam, hiddenpower, earthpower
.hword 291, 50, quagsire, leftovers, scald, earthquake, recover, curse
.hword 292, 50, quagsire, sitrusberry, icepunch, earthquake, recover, curse
.hword 293, 50, quagsire, sitrusberry, yawn, waterfall, recover, earthquake
.hword 294, 50, quagsire, leftovers, toxic, protect, earthquake, recover
.hword 295, 50, espeon, choicespecs, psyshock, grassknot, shadowball, dazzlinggleam
.hword 296, 50, espeon, sitrusberry, calmmind, morningsun, storedpower, dazzlinggleam
.hword 297, 50, espeon, focussash, psychic, yawn, shadowball, hiddenpower
.hword 298, 50, espeon, focussash, calmmind, storedpower, yawn, batonpass
.hword 299, 50, umbreon, leftovers, foulplay, snarl, healbell, moonlight
.hword 300, 50, umbreon, lumberry, foulplay, snarl, toxic, rest
.hword 301, 50, umbreon, magoberry, darkpulse, snarl, charm, toxic
.hword 302, 50, umbreon, leftovers, curse, suckerpunch, snarl, rest
.hword 303, 50, slowking, wikiberry, psychic, surf, fireblast, slackoff
.hword 304, 50, slowking, assaultvest, psychic, surf, flamethrower, icebeam
.hword 305, 50, slowking, sitrusberry, psychic, icebeam, slackoff, calmmind
.hword 306, 50, slowking, weaknesspolicy, surf, icebeam, earthquake, yawn
.hword 307, 50, forretress, sitrusberry, stealthrock, spikes, toxicspikes, ironhead
.hword 308, 50, forretress, assaultvest, voltswitch, ironhead, earthquake, bugbite
.hword 309, 50, forretress, leftovers, bodypress, stealthrock, ironhead, spikes
.hword 310, 50, forretress, leftovers, bodypress, spikes, toxic, protect
.hword 311, 50, steelix, quickclaw, irontail, stoneedge, earthquake, explosion
.hword 312, 50, steelix, lifeorb, ironhead, rockslide, earthquake, crunch
.hword 313, 50, steelix, sitrusberry, earthquake, stealthrock, roar, rest
.hword 314, 50, steelix, leftovers, bodypress, sandtomb, toxic, rest
.hword 315, 50, granbull, choiceband, playrough, closecombat, earthquake, crunch
.hword 316, 50, granbull, assaultvest, playrough, crunch, firepunch, icepunch
.hword 317, 50, granbull, muscleband, playrough, thunderwave, earthquake, crunch
.hword 318, 50, granbull, kingsrock, playrough, thunderwave, attract, earthquake
.hword 319, 50, scizor, occaberry, bulletpunch, bugbite, swordsdance, roost
.hword 320, 50, scizor, assaultvest, bulletpunch, uturn, swordsdance, knockoff
.hword 321, 50, scizor, sitrusberry, bulletpunch, uturn, roost, superpower
.hword 322, 50, scizor, choiceband, bulletpunch, furycutter, superpower, knockoff
.hword 323, 50, shuckle, figyberry, stickyweb, stealthrock, toxic, knockoff
.hword 324, 50, shuckle, wikiberry, toxic, rollout, strugglebug, protect
.hword 325, 50, shuckle, chestoberry, toxic, wrap, strugglebug, rest
.hword 326, 50, shuckle, leftovers, rocktomb, strugglebug, toxic, stealthrock
.hword 327, 50, heracross, choiceband, megahorn, closecombat, earthquake, rockslide
.hword 328, 50, heracross, flameorb, megahorn, closecombat, earthquake, protect
.hword 329, 50, heracross, cobaberry, megahorn, closecombat, rockslide, swordsdance
.hword 330, 50, heracross, salacberry, megahorn, reversal, endure, swordsdance
.hword 331, 50, magcargo, sitrusberry, stealthrock, recover, yawn, flamethrower
.hword 332, 50, magcargo, passhoberry, shellsmash, rockslide, earthpower, flamethrower
.hword 333, 50, magcargo, focussash, shellsmash, rockslide, earthquake, overheat
.hword 334, 50, magcargo, sitrusberry, willowisp, acidarmor, rockslide, recover
.hword 335, 50, octillery, choicespecs, surf, fireblast, icebeam, energyball
.hword 336, 50, octillery, choicescarf, waterspout, fireblast, sludgebomb, blizzard
.hword 337, 50, octillery, sitrusberry, scald, acidspray, icebeam, protect
.hword 338, 50, octillery, assaultvest, waterfall, seedbomb, gunkshot, bounce
.hword 339, 50, mantine, wacanberry, scald, airslash, earthquake, roost
.hword 340, 50, mantine, chartiberry, surf, icebeam, earthquake, roost
.hword 341, 50, mantine, iapapaberry, scald, roost, toxic, haze
.hword 342, 50, mantine, iapapaberry, mirrorcoat, toxic, protect, dive
.hword 343, 50, skarmory, choiceband, bravebird, ironhead, rockslide, earthquake
.hword 344, 50, skarmory, rockyhelmet, drillpeck, stealthrock, whirlwind, roost
.hword 345, 50, skarmory, rockyhelmet, bodypress, irondefense, toxic, roost
.hword 346, 50, skarmory, leftovers, drillpeck, steelwing, swordsdance, earthquake
.hword 347, 50, houndoom, focussash, darkpulse, flamethrower, nastyplot, sludgebomb
.hword 348, 50, houndoom, chopleberry, darkpulse, fireblast, sunnyday, solarbeam
.hword 349, 50, houndoom, sitrusberry, foulplay, overheat, toxic, roar
.hword 350, 50, houndoom, weaknesspolicy, reversal, suckerpunch, endure, overheat
.hword 351, 50, kingdra, damprock, hydropump, dracometeor, icebeam, raindance
.hword 352, 50, kingdra, scopelens, surf, dracometeor, icebeam, focusenergy
.hword 353, 50, kingdra, whiteherb, waterfall, dracometeor, frustration, dragondance
.hword 354, 50, kingdra, chestoberry, surf, dragonpulse, yawn, rest
.hword 355, 50, donphan, assaultvest, earthquake, playrough, seedbomb, iceshard
.hword 356, 50, donphan, choiceband, earthquake, playrough, rockslide, knockoff
.hword 357, 50, donphan, passhoberry, earthquake, rockslide, gunkshot, iceshard
.hword 358, 50, donphan, focusband, earthquake, counter, endeavor, iceshard
.hword 359, 50, smeargle, chopleberry, bellydrum, extremespeed, spore, batonpass
.hword 360, 50, smeargle, focusband, stickyweb, nuzzle, seismictoss, toxicspikes
.hword 361, 50, smeargle, focusband, psychoboost, spore, uturn, superpower
.hword 362, 50, smeargle, focussash, shellsmash, storedpower, spore, substitute
.hword 363, 50, hitmontop, assaultvest, closecombat, fakeout, counter, machpunch
.hword 364, 50, hitmontop, weaknesspolicy, triplekick, earthquake, suckerpunch, machpunch
.hword 365, 50, hitmontop, assaultvest, thief, counter, machpunch, closecombat
.hword 366, 50, hitmontop, lifeorb, rockslide, earthquake, closecombat, machpunch
.hword 367, 50, miltank, figyberry, charm, earthquake, doubleedge, playrough
.hword 368, 50, miltank, rockyhelmet, curse, bodyslam, milkdrink, thunderpunch
.hword 369, 50, miltank, choiceband, bodyslam, thunderpunch, icepunch, firepunch
.hword 370, 50, miltank, leftovers, headbutt, thunderwave, attract, playrough
.hword 371, 50, blissey, leftovers, calmmind, icebeam, thunderbolt, softboiled
.hword 372, 50, blissey, chopleberry, minimize, softboiled, psychic, icebeam
.hword 373, 50, blissey, magoberry, seismictoss, thunderwave, softboiled, minimize
.hword 374, 50, blissey, iapapaberry, toxic, minimize, psychic, softboiled
.hword 375, 50, raikou, shucaberry, thunderbolt, scald, aurasphere, calmmind
.hword 376, 50, raikou, choicespecs, thunderbolt, scald, aurasphere, shadowball
.hword 377, 50, entei, assaultvest, sacredfire, crunch, stoneedge, extremespeed
.hword 378, 50, entei, whiteherb, overheat, sacredfire, stoneedge, bulldoze
.hword 379, 50, suicune, assaultvest, scald, icebeam, snarl, bulldoze
.hword 380, 50, suicune, chestoberry, scald, icebeam, calmmind, rest
.hword 381, 50, tyranitar, sitrusberry, stoneedge, crunch, earthquake, thunderwave
.hword 382, 50, tyranitar, lumberry, dragondance, crunch, rockslide, earthquake
.hword 383, 50, tyranitar, wiseglasses, darkpulse, icebeam, flamethrower, thunderwave
.hword 384, 50, tyranitar, choicescarf, stoneedge, crunch, firepunch, icepunch
.hword 385, 50, leafeon, assaultvest, leafblade, irontail, dig, quickattack
.hword 386, 50, leafeon, salacberry, leafblade, sunnyday, growth, dig
.hword 387, 50, leafeon, lumberry, leafblade, swordsdance, xscissor, yawn
.hword 388, 50, leafeon, muscleband, leafblade, swordsdance, xscissor, dig
.hword 389, 50, glaceon, choicescarf, icebeam, shadowball, mirrorcoat, hyperbeam
.hword 390, 50, glaceon, expertbelt, freezedry, shadowball, waterpulse, yawn
.hword 391, 50, glaceon, leftovers, hail, blizzard, wish, waterpulse
.hword 392, 50, glaceon, brightpowder, hail, blizzard, doubleteam, protect
.hword 393, 50, sylveon, sitrusberry, hypervoice, quickattack, calmmind, shadowball
.hword 394, 50, sylveon, lumberry, hypervoice, mysticalfire, calmmind, shadowball
.hword 395, 50, sylveon, muscleband, bodyslam, quickattack, bite, yawn
.hword 396, 50, sylveon, babiriberry, moonblast, calmmind, shadowball, mysticalfire
.hword 397, 50, honchkrow, focussash, suckerpunch, drillpeck, superpower, thunderwave
.hword 398, 50, honchkrow, scopelens, heatwave, psychic, superpower, darkpulse
.hword 399, 50, honchkrow, wacanberry, thunderwave, airslash, foulplay, roost
.hword 400, 50, honchkrow, lifeorb, bravebird, suckerpunch, superpower, heatwave
.hword 401, 50, mismagius, choicespecs, shadowball, mysticalfire, dazzlinggleam, energyball
.hword 402, 50, mismagius, colburberry, shadowball, dazzlinggleam, nastyplot, psychic
.hword 403, 50, mismagius, expertbelt, shadowball, thunderbolt, nastyplot, energyball
.hword 404, 50, mismagius, leftovers, shadowball, painsplit, thunderwave, confuseray
.hword 405, 50, gliscor, yacheberry, earthquake, acrobatics, swordsdance, skyuppercut
.hword 406, 50, gliscor, expertbelt, earthquake, firefang, thunderfang, icefang
.hword 407, 50, gliscor, toxicorb, earthquake, knockoff, swordsdance, roost
.hword 408, 50, gliscor, toxicorb, earthquake, toxic, protect, roost
.hword 409, 50, weavile, focussash, iciclecrash, knockoff, fakeout, swordsdance
.hword 410, 50, weavile, lifeorb, iciclecrash, knockoff, lowkick, iceshard
.hword 411, 50, weavile, focussash, icepunch, knockoff, swordsdance, poisonjab
.hword 412, 50, weavile, expertbelt, icepunch, knockoff, swordsdance, lowkick
.hword 413, 50, togekiss, sitrusberry, airslash, dazzlinggleam, thunderwave, flamethrower
.hword 414, 50, togekiss, choicespecs, airslash, dazzlinggleam, aurasphere, flamethrower
.hword 415, 50, togekiss, scopelens, airslash, flamethrower, dazzlinggleam, nastyplot
.hword 416, 50, togekiss, leftovers, airslash, flamethrower, thunderwave, roost
.hword 417, 50, magnezone, shucaberry, thunderbolt, flashcannon, thunderwave, mirrorcoat
.hword 418, 50, magnezone, metalcoat, thunderbolt, flashcannon, thunderwave, hiddenpower
.hword 419, 50, magnezone, choicespecs, voltswitch, flashcannon, hyperbeam, bodypress
.hword 420, 50, magnezone, wiseglasses, voltswitch, flashcannon, thunderwave, signalbeam
.hword 421, 50, magmortar, passhoberry, flamethrower, thunderbolt, psychic, willowisp
.hword 422, 50, magmortar, heatrock, flamethrower, solarbeam, focusblast, sunnyday
.hword 423, 50, magmortar, shucaberry, flamethrower, thunderbolt, focusblast, confuseray
.hword 424, 50, magmortar, muscleband, overheat, thunderpunch, flareblitz, earthquake
.hword 425, 50, electivire, choiceband, wildcharge, icepunch, earthquake, crosschop
.hword 426, 50, electivire, magnet, wildcharge, voltswitch, earthquake, firepunch
.hword 427, 50, electivire, shucaberry, wildcharge, thunderwave, earthquake, icepunch
.hword 428, 50, electivire, widelens, thunder, flamethrower, psychic, focusblast
.hword 429, 50, rhyperior, assaultvest, earthquake, stoneedge, megahorn, avalanche
.hword 430, 50, rhyperior, lifeorb, earthquake, rockslide, rockpolish, megahorn
.hword 431, 50, rhyperior, choicescarf, earthquake, rockslide, thunderpunch, icepunch
.hword 432, 50, rhyperior, choiceband, earthquake, rockwrecker, crunch, icepunch
.hword 433, 50, raichualolan, wiseglasses, thunderbolt, psychic, grassknot, nuzzle
.hword 434, 50, raichualolan, focussash, thunderbolt, psychic, focusblast, fakeout
.hword 435, 50, sandslashalolan, choiceband, iciclecrash, ironhead, rockslide, earthquake
.hword 436, 50, sandslashalolan, assaultvest, iciclecrash, ironhead, poisonjab, xscissor
.hword 437, 50, ninetalesalolan, expertbelt, blizzard, dazzlinggleam, auroraveil, foulplay
.hword 438, 50, ninetalesalolan, nevermeltice, freezedry, blizzard, auroraveil, dazzlinggleam
.hword 439, 50, dugtrioalolan, choiceband, earthquake, ironhead, rockslide, shadowclaw
.hword 440, 50, dugtrioalolan, focussash, earthquake, ironhead, reversal, suckerpunch
.hword 441, 50, persianalolan, assaultvest, fakeout, foulplay, snarl, uturn
.hword 442, 50, persianalolan, lifeorb, fakeout, foulplay, thunderbolt, powergem
.hword 443, 50, golemalolan, choicescarf, rockslide, wildcharge, earthquake, firepunch
.hword 444, 50, golemalolan, magnet, stoneedge, voltswitch, earthquake, wildcharge
.hword 445, 50, mukalolan, figyberry, poisonjab, knockoff, minimize, rocktomb
.hword 446, 50, mukalolan, blacksludge, acidspray, snarl, minimize, rest
.hword 447, 50, exeggutoralolan, yacheberry, dragonhammer, brickbreak, leafstorm, trickroom
.hword 448, 50, exeggutoralolan, choiceband, dragonhammer, woodhammer, earthquake, fireblast
.hword 449, 50, marowakalolan, thickclub, shadowbone, flareblitz, bulldoze, thunderpunch
.hword 450, 50, marowakalolan, thickclub, shadowbone, flareblitz, earthquake, brickbreak
.hword 451, 50, rapidashgalarian, choiceband, playrough, psychocut, megahorn, hihorsepower
.hword 452, 50, rapidashgalarian, kebiaberry, playrough, psychocut, hypnosis, hihorsepower
.hword 453, 50, slowbrogalarian, quickclaw, shellsidearm, icebeam, psychic, slackoff
.hword 454, 50, slowbrogalarian, quickclaw, shellsidearm, calmmind, psyshock, slackoff
.hword 455, 50, slowkinggalarian, assaultvest, eeriespell, flamethrower, sludgebomb, icebeam
.hword 456, 50, slowkinggalarian, sitrusberry, eeriespell, earthquake, sludgebomb, trickroom
.hword 457, 50, sirfetchd, stick, leafblade, nightslash, closecombat, bravebird
.hword 458, 50, sirfetchd, stick, leafblade, knockoff, closecombat, quickattack
.hword 459, 50, sirfetchd, stick, swordsdance, leafblade, nightslash, closecombat
.hword 460, 50, sirfetchd, stick, knockoff, leafblade, meteorassault, irondefense
.hword 461, 50, weezinggalarian, choicespecs, strangesteam, sludgebomb, thunderbolt, flamethrower
.hword 462, 50, weezinggalarian, payapaberry, strangesteam, sludgebomb, darkpulse, destinybond
.hword 463, 50, mrrime, wiseglasses, icebeam, psychic, teeterdance, thunderbolt
.hword 464, 50, mrrime, choicespecs, freezedry, psychic, focusblast, shadowball
.hword 465, 50, mrrime, leftovers, icebeam, toxic, slackoff, protect
.hword 466, 50, mrrime, choicescarf, freezedry, dazzlinggleam, energyball, thunderbolt
.hword 467, 50, articunogalarian, sitrusberry, freezeglare, airslash, calmmind, recover
.hword 468, 50, articunogalarian, weaknesspolicy, freezeglare, airslash, steelwing, recover
.hword 469, 50, zapdosgalarian, choiceband, thunderkick, bravebird, uturn, drillrun
.hword 470, 50, zapdosgalarian, wacanberry, thunderkick, drillpeck, bulkup, roost
.hword 471, 50, moltresgalarian, sitrusberry, fierywrath, airslash, ancientpower, nastyplot
.hword 472, 50, moltresgalarian, lifeorb, fierywrath, airslash, nastyplot, roost
.hword 473, 50, cursola, choicespecs, shadowball, scald, powergem, gigadrain
.hword 474, 50, cursola, quickclaw, shadowball, icebeam, earthpower, surf
.hword 475, 50, cursola, colburberry, shadowball, painsplit, protect, gigadrain
.hword 476, 50, cursola, quickclaw, shadowball, hydropump, powergem, icebeam
.hword 477, 50, arcaninehisuian, passhoberry, ragingfury, rockslide, extremespeed, crunch
.hword 478, 50, arcaninehisuian, choiceband, ragingfury, closecombat, playrough, rockslide
.hword 479, 50, electrodehisuian, occaberry, chloroblast, thunderbolt, foulplay, thunderwave
.hword 480, 50, electrodehisuian, damprock, chloroblast, thunder, toxic, raindance
.hword 481, 50, kleavor, assaultvest, stoneaxe, xscissor, knockoff, quickattack
.hword 482, 50, kleavor, lifeorb, stoneaxe, xscissor, swordsdance, roost
.hword 483, 50, kleavor, lifeorb, stoneaxe, uturn, swordsdance, superpower
.hword 484, 50, kleavor, sitrusberry, stoneaxe, uturn, swordsdance, quickattack
.hword 485, 50, typhlosionhisuian, choicespecs, shadowball, flamethrower, extrasensory, focusblast
.hword 486, 50, typhlosionhisuian, leftovers, willowisp, infernalparade, earthquake, flamethrower
.hword 487, 50, overqwil, expertbelt, poisonjab, foulplay, waterfall, destinybond
.hword 488, 50, overqwil, blacksludge, toxic, dive, protect, barbbarrage
.hword 489, 50, overqwil, focusband, poisonjab, revenge, aquajet, destinybond
.hword 490, 50, overqwil, choicespecs, acidspray, darkpulse, icebeam, hydropump
.hword 491, 50, sneasler, choiceband, closecombat, direclaw, shadowclaw, xscissor
.hword 492, 50, sneasler, payapaberry, closecombat, direclaw, quickattack, swordsdance
.hword 493, 50, sneasler, focussash, closecombat, poisonjab, fakeout, shadowclaw
.hword 494, 50, sneasler, muscleband, closecombat, poisonjab, fakeout, swordsdance
.hword 495, 50, ursaluna, flameorb, headlongrush, facade, protect, playrough
.hword 496, 50, ursaluna, assaultvest, headlongrush, crunch, playrough, rockslide
.hword 497, 50, ursaluna, flameorb, earthquake, facade, protect, thunderpunch
.hword 498, 50, ursaluna, choicescarf, earthquake, doubleedge, crunch, closecombat
.hword 499, 50, wyrdeer, choiceband, psyshieldbash, wildcharge, earthquake, megahorn
.hword 500, 50, wyrdeer, leftovers, psyshieldbash, hypnosis, confuseray, jumpkick
.hword 501, 50, wyrdeer, expertbelt, psyshieldbash, jumpkick, earthquake, doubleedge
.hword 502, 50, wyrdeer, leftovers, psyshieldbash, earthquake, confuseray, hypnosis
.hword 503, 50, porygonz, expertbelt, triattack, icebeam, thunderbolt, darkpulse
.hword 504, 50, porygonz, choicescarf, triattack, icebeam, psychic, shadowball
.hword 505, 50, porygonz, choicespecs, hyperbeam, icebeam, psychic, darkpulse
.hword 506, 50, porygonz, focussash, triattack, foulplay, nastyplot, recover
.hword 507, 50, yanmega, lifeorb, airslash, bugbuzz, protect, ancientpower
.hword 508, 50, yanmega, choicespecs, airslash, bugbuzz, psychic, gigadrain
.hword 509, 50, yanmega, focussash, airslash, uturn, hypnosis, dreameater
.hword 510, 50, yanmega, assaultvest, airslash, bugbuzz, shadowball, ancientpower
.hword 511, 50, mamoswine, choiceband, earthquake, iciclecrash, rocktomb, knockoff
.hword 512, 50, mamoswine, passhoberry, earthquake, iciclecrash, iceshard, superpower
.hword 513, 50, mamoswine, lifeorb, earthquake, iciclecrash, knockoff, iceshard
.hword 514, 50, mamoswine, assaultvest, earthquake, iciclecrash, rockslide, knockoff
.hword 515, 50, ambipom, silkscarf, fakeout, doublehit, uturn, aerialace
.hword 516, 50, ambipom, chopleberry, fakeout, nastyplot, swift, batonpass
.hword 517, 50, ambipom, expertbelt, fakeout, icepunch, uturn, thunderpunch
.hword 518, 50, ambipom, lifeorb, fakeout, knockoff, uturn, lowkick
.hword 519, 50, lickilicky, weaknesspolicy, surf, powerwhip, thrash, earthquake
.hword 520, 50, lickilicky, leftovers, wish, knockoff, toxic, protect
.hword 521, 50, lickilicky, quickclaw, icebeam, thunderbolt, flamethrower, earthquake
.hword 522, 50, lickilicky, sitrusberry, bellydrum, knockoff, earthquake, bodyslam
.hword 523, 50, tangrowth, choiceband, powerwhip, knockoff, earthquake, rockslide
.hword 524, 50, tangrowth, leftovers, gigadrain, protect, earthquake, leechseed
.hword 525, 50, tangrowth, leftovers, knockoff, earthquake, sleeppowder, leechseed
.hword 526, 50, tangrowth, quickclaw, leafstorm, knockoff, sludgebomb, focusblast
.hword 527, 50, perrserker, metalcoat, fakeout, ironhead, counter, uturn
.hword 528, 50, perrserker, quickclaw, fakeout, ironhead, playrough, crosschop
.hword 529, 50, perrserker, choiceband, ironhead, playrough, crosschop, gunkshot
.hword 530, 50, perrserker, quickclaw, fakeout, ironhead, seedbomb, crosschop

.hword 531, 50, tauroscombat, choiceband, ragingbull, earthquake, rockslide, zenheadbutt                      
.hword 532, 50, tauroscombat, sitrusberry, ragingbull, earthquake, ironhead, substitute                       
.hword 533, 50, taurosblaze, choiceband, ragingbull, closecombat, earthquake, wildcharge                      
.hword 534, 50, taurosblaze, sitrusberry, ragingbull, brickbreak, rockslide, substitute                       
.hword 535, 50, taurosaqua, choiceband, ragingbull, closecombat, rockslide, earthquake                        
.hword 536, 50, taurosaqua, sitrusberry, ragingbull, brickbreak, earthquake, substitute                       
.hword 537, 50, wugtrio, focussash, tripledive, dig, suckerpunch, reversal                                    
.hword 538, 50, wugtrio, expertbelt, tripledive, dig, foulplay, blizzard                                      
.hword 539, 50, toedscruel, yacheberry, earthpower, gigadrain, spore, trickroom                               
.hword 540, 50, toedscruel, expertbelt, earthpower, gigadrain, flashcannon, dazzlinggleam                     
.hword 541, 50, clodsire, leftovers, toxic, earthquake, recover, stealthrock                                  
.hword 542, 50, clodsire, leftovers, earthquake, poisonjab, yawn, stealthrock                                 
.hword 543, 50, dudunsparce, sitrusberry, coil, roost, hyperdrill, drillrun                                   
.hword 544, 50, dudunsparce, muscleband, glare, hyperdrill, drillrun, rockslide                               
.hword 545, 50, dudunsparce, widelens, glare, airslash, blizzard, fireblast                                   
.hword 546, 50, dudunsparce, leftovers, glare, rockslide, airslash, roost                                     
.hword 547, 50, farigiraf, weaknesspolicy, earthquake, lowkick, twinbeam, thunderbolt                         
.hword 548, 50, farigiraf, sitrusberry, nastyplot, twinbeam, thunderbolt, hypervoice                          
.hword 549, 50, farigiraf, leftovers, trickroom, twinbeam, foulplay, earthquake                               
.hword 550, 50, farigiraf, wikiberry, trickroom, darkpulse, twinbeam, thunderbolt                             
.hword 551, 50, screamtail, boosterenergy, dazzlinggleam, disable, encore, psychic                            
.hword 552, 50, screamtail, boosterenergy, calmmind, dazzlinggleam, flamethrower, thunderbolt                 
.hword 553, 50, fluttermane, boosterenergy, moonblast, shadowball, energyball, powergem                       
.hword 554, 50, fluttermane, boosterenergy, moonblast, shadowball, mysticalfire, thunderbolt                  
.hword 555, 50, sandyshocks, boosterenergy, earthpower, thunderbolt, irondefense, bodypress                   
.hword 556, 50, sandyshocks, boosterenergy, earthpower, thunderbolt, powergem, thunderwave                    
.hword 557, 50, greattusk, boosterenergy, closecombat, headlongrush, headsmash, knockoff                      
.hword 558, 50, greattusk, boosterenergy, closecombat, earthquake, icefang, thunderfang                       
.hword 559, 50, irontreads, boosterenergy, ironhead, earthquake, knockoff, wildcharge                         
.hword 560, 50, irontreads, boosterenergy, ironhead, earthquake, voltswitch, rockslide                        
.hword 561, 50, ironbundle, boosterenergy, hydropump, blizzard, freezedry, encore                             
.hword 562, 50, ironbundle, boosterenergy, hydropump, icebeam, freezedry, uturn                               
.hword 563, 50, ironthorns, boosterenergy, wildcharge, rockblast, pinmissile, dragondance                      
.hword 564, 50, ironthorns, boosterenergy, wildcharge, earthquake, rockslide, icepunch                        
.hword 565, 50, walkingwake, boosterenergy, hydrosteam, snarl, icebeam, flamethrower                          
.hword 566, 50, walkingwake, boosterenergy, hydrosteam, dracometeor, flamethrower, sunnyday                   


// come back to these later


.hword 567, 50, 0, 0, 0, 0, 0, 0
.hword 568, 50, 0, 0, 0, 0, 0, 0
.hword 569, 50, 0, 0, 0, 0, 0, 0
.hword 570, 50, 0, 0, 0, 0, 0, 0
.hword 571, 50, 0, 0, 0, 0, 0, 0
.hword 572, 50, 0, 0, 0, 0, 0, 0
.hword 573, 50, 0, 0, 0, 0, 0, 0
.hword 574, 50, 0, 0, 0, 0, 0, 0
.hword 575, 50, 0, 0, 0, 0, 0, 0
.hword 576, 50, 0, 0, 0, 0, 0, 0
.hword 577, 50, 0, 0, 0, 0, 0, 0
.hword 578, 50, 0, 0, 0, 0, 0, 0
.hword 579, 50, 0, 0, 0, 0, 0, 0
.hword 580, 50, 0, 0, 0, 0, 0, 0
.hword 581, 50, 0, 0, 0, 0, 0, 0
.hword 582, 50, 0, 0, 0, 0, 0, 0
.hword 583, 50, 0, 0, 0, 0, 0, 0
.hword 584, 50, 0, 0, 0, 0, 0, 0
.hword 585, 50, 0, 0, 0, 0, 0, 0
.hword 586, 50, 0, 0, 0, 0, 0, 0
.hword 587, 50, 0, 0, 0, 0, 0, 0
.hword 588, 50, 0, 0, 0, 0, 0, 0
.hword 589, 50, 0, 0, 0, 0, 0, 0
.hword 590, 50, 0, 0, 0, 0, 0, 0
.hword 591, 50, 0, 0, 0, 0, 0, 0
.hword 592, 50, 0, 0, 0, 0, 0, 0
.hword 593, 50, 0, 0, 0, 0, 0, 0
.hword 594, 50, 0, 0, 0, 0, 0, 0
.hword 595, 50, 0, 0, 0, 0, 0, 0
.hword 596, 50, 0, 0, 0, 0, 0, 0
.hword 597, 50, 0, 0, 0, 0, 0, 0
.hword 598, 50, 0, 0, 0, 0, 0, 0
.hword 599, 50, 0, 0, 0, 0, 0, 0
.hword 600, 50, 0, 0, 0, 0, 0, 0
.hword 601, 50, 0, 0, 0, 0, 0, 0
.hword 602, 50, 0, 0, 0, 0, 0, 0
.hword 603, 50, 0, 0, 0, 0, 0, 0
.hword 604, 50, 0, 0, 0, 0, 0, 0
.hword 605, 50, 0, 0, 0, 0, 0, 0
.hword 606, 50, 0, 0, 0, 0, 0, 0
.hword 607, 50, 0, 0, 0, 0, 0, 0
.hword 608, 50, 0, 0, 0, 0, 0, 0
.hword 609, 50, 0, 0, 0, 0, 0, 0
.hword 610, 50, 0, 0, 0, 0, 0, 0
.hword 611, 50, 0, 0, 0, 0, 0, 0
.hword 612, 50, 0, 0, 0, 0, 0, 0
.hword 613, 50, 0, 0, 0, 0, 0, 0
.hword 614, 50, 0, 0, 0, 0, 0, 0
.hword 615, 50, 0, 0, 0, 0, 0, 0
.hword 616, 50, 0, 0, 0, 0, 0, 0
.hword 617, 50, 0, 0, 0, 0, 0, 0
.hword 618, 50, 0, 0, 0, 0, 0, 0
.hword 619, 50, 0, 0, 0, 0, 0, 0
.hword 620, 50, 0, 0, 0, 0, 0, 0
.hword 621, 50, 0, 0, 0, 0, 0, 0
.hword 622, 50, 0, 0, 0, 0, 0, 0
.hword 623, 50, 0, 0, 0, 0, 0, 0
.hword 624, 50, 0, 0, 0, 0, 0, 0
.hword 625, 50, 0, 0, 0, 0, 0, 0
.hword 626, 50, 0, 0, 0, 0, 0, 0
.hword 627, 50, 0, 0, 0, 0, 0, 0
.hword 628, 50, 0, 0, 0, 0, 0, 0
.hword 629, 50, 0, 0, 0, 0, 0, 0
.hword 630, 50, 0, 0, 0, 0, 0, 0
.hword 631, 50, 0, 0, 0, 0, 0, 0
.hword 632, 50, 0, 0, 0, 0, 0, 0
.hword 633, 50, 0, 0, 0, 0, 0, 0
.hword 634, 50, 0, 0, 0, 0, 0, 0
.hword 635, 50, 0, 0, 0, 0, 0, 0
.hword 636, 50, 0, 0, 0, 0, 0, 0
.hword 637, 50, 0, 0, 0, 0, 0, 0
.hword 638, 50, 0, 0, 0, 0, 0, 0
.hword 639, 50, 0, 0, 0, 0, 0, 0
.hword 640, 50, 0, 0, 0, 0, 0, 0
.hword 641, 50, 0, 0, 0, 0, 0, 0
.hword 642, 50, 0, 0, 0, 0, 0, 0
.hword 643, 50, 0, 0, 0, 0, 0, 0
.hword 644, 50, 0, 0, 0, 0, 0, 0
.hword 645, 50, 0, 0, 0, 0, 0, 0
.hword 646, 50, 0, 0, 0, 0, 0, 0
.hword 647, 50, 0, 0, 0, 0, 0, 0
.hword 648, 50, 0, 0, 0, 0, 0, 0
.hword 649, 50, 0, 0, 0, 0, 0, 0
.hword 650, 50, 0, 0, 0, 0, 0, 0
.hword 651, 50, 0, 0, 0, 0, 0, 0
.hword 652, 50, 0, 0, 0, 0, 0, 0
.hword 653, 50, 0, 0, 0, 0, 0, 0
.hword 654, 50, 0, 0, 0, 0, 0, 0
.hword 655, 50, 0, 0, 0, 0, 0, 0
.hword 656, 50, 0, 0, 0, 0, 0, 0
.hword 657, 50, 0, 0, 0, 0, 0, 0
.hword 658, 50, 0, 0, 0, 0, 0, 0
.hword 659, 50, 0, 0, 0, 0, 0, 0
.hword 660, 50, 0, 0, 0, 0, 0, 0
.hword 661, 50, 0, 0, 0, 0, 0, 0
.hword 662, 50, 0, 0, 0, 0, 0, 0
.hword 663, 50, 0, 0, 0, 0, 0, 0
.hword 664, 50, 0, 0, 0, 0, 0, 0
.hword 665, 50, 0, 0, 0, 0, 0, 0
.hword 666, 50, 0, 0, 0, 0, 0, 0
.hword 667, 50, 0, 0, 0, 0, 0, 0
.hword 668, 50, 0, 0, 0, 0, 0, 0
.hword 669, 50, 0, 0, 0, 0, 0, 0
.hword 670, 50, 0, 0, 0, 0, 0, 0
.hword 671, 50, 0, 0, 0, 0, 0, 0
.hword 672, 50, 0, 0, 0, 0, 0, 0
.hword 673, 50, 0, 0, 0, 0, 0, 0
.hword 674, 50, 0, 0, 0, 0, 0, 0
.hword 675, 50, 0, 0, 0, 0, 0, 0
.hword 676, 50, 0, 0, 0, 0, 0, 0
.hword 677, 50, 0, 0, 0, 0, 0, 0
.hword 678, 50, 0, 0, 0, 0, 0, 0
.hword 679, 50, 0, 0, 0, 0, 0, 0
.hword 680, 50, 0, 0, 0, 0, 0, 0
.hword 681, 50, 0, 0, 0, 0, 0, 0
.hword 682, 50, 0, 0, 0, 0, 0, 0
.hword 683, 50, 0, 0, 0, 0, 0, 0
.hword 684, 50, 0, 0, 0, 0, 0, 0
.hword 685, 50, 0, 0, 0, 0, 0, 0
.hword 686, 50, 0, 0, 0, 0, 0, 0
.hword 687, 50, 0, 0, 0, 0, 0, 0
.hword 688, 50, 0, 0, 0, 0, 0, 0
.hword 689, 50, 0, 0, 0, 0, 0, 0
.hword 690, 50, 0, 0, 0, 0, 0, 0
.hword 691, 50, 0, 0, 0, 0, 0, 0
.hword 692, 50, 0, 0, 0, 0, 0, 0
.hword 693, 50, 0, 0, 0, 0, 0, 0
.hword 694, 50, 0, 0, 0, 0, 0, 0
.hword 695, 50, 0, 0, 0, 0, 0, 0
.hword 696, 50, 0, 0, 0, 0, 0, 0
.hword 697, 50, 0, 0, 0, 0, 0, 0
.hword 698, 50, 0, 0, 0, 0, 0, 0
.hword 699, 50, 0, 0, 0, 0, 0, 0
.hword 700, 50, 0, 0, 0, 0, 0, 0
.hword 701, 50, 0, 0, 0, 0, 0, 0
.hword 702, 50, 0, 0, 0, 0, 0, 0
.hword 703, 50, 0, 0, 0, 0, 0, 0
.hword 704, 50, 0, 0, 0, 0, 0, 0
.hword 705, 50, 0, 0, 0, 0, 0, 0
.hword 706, 50, 0, 0, 0, 0, 0, 0
.hword 707, 50, 0, 0, 0, 0, 0, 0
.hword 708, 50, 0, 0, 0, 0, 0, 0
.hword 709, 50, 0, 0, 0, 0, 0, 0
.hword 710, 50, 0, 0, 0, 0, 0, 0
.hword 711, 50, 0, 0, 0, 0, 0, 0
.hword 712, 50, 0, 0, 0, 0, 0, 0
.hword 713, 50, 0, 0, 0, 0, 0, 0
.hword 714, 50, 0, 0, 0, 0, 0, 0
.hword 715, 50, 0, 0, 0, 0, 0, 0
.hword 716, 50, 0, 0, 0, 0, 0, 0
.hword 717, 50, 0, 0, 0, 0, 0, 0
.hword 718, 50, 0, 0, 0, 0, 0, 0
.hword 719, 50, 0, 0, 0, 0, 0, 0
.hword 720, 50, 0, 0, 0, 0, 0, 0
.hword 721, 50, 0, 0, 0, 0, 0, 0
.hword 722, 50, 0, 0, 0, 0, 0, 0
.hword 723, 50, 0, 0, 0, 0, 0, 0
.hword 724, 50, 0, 0, 0, 0, 0, 0
.hword 725, 50, 0, 0, 0, 0, 0, 0
.hword 726, 50, 0, 0, 0, 0, 0, 0
.hword 727, 50, 0, 0, 0, 0, 0, 0
.hword 728, 50, 0, 0, 0, 0, 0, 0
.hword 729, 50, 0, 0, 0, 0, 0, 0
.hword 730, 50, 0, 0, 0, 0, 0, 0
.hword 731, 50, 0, 0, 0, 0, 0, 0
.hword 732, 50, 0, 0, 0, 0, 0, 0
.hword 733, 50, 0, 0, 0, 0, 0, 0
.hword 734, 50, 0, 0, 0, 0, 0, 0
.hword 735, 50, 0, 0, 0, 0, 0, 0
.hword 736, 50, 0, 0, 0, 0, 0, 0
.hword 737, 50, 0, 0, 0, 0, 0, 0
.hword 738, 50, 0, 0, 0, 0, 0, 0
.hword 739, 50, 0, 0, 0, 0, 0, 0
.hword 740, 50, 0, 0, 0, 0, 0, 0
.hword 741, 50, 0, 0, 0, 0, 0, 0
.hword 742, 50, 0, 0, 0, 0, 0, 0
.hword 743, 50, 0, 0, 0, 0, 0, 0
.hword 744, 50, 0, 0, 0, 0, 0, 0
.hword 745, 50, 0, 0, 0, 0, 0, 0
.hword 746, 50, 0, 0, 0, 0, 0, 0
.hword 747, 50, 0, 0, 0, 0, 0, 0
.hword 748, 50, 0, 0, 0, 0, 0, 0
.hword 749, 50, 0, 0, 0, 0, 0, 0
.hword 750, 50, 0, 0, 0, 0, 0, 0
.hword 751, 50, 0, 0, 0, 0, 0, 0
.hword 752, 50, 0, 0, 0, 0, 0, 0
.hword 753, 50, 0, 0, 0, 0, 0, 0
.hword 754, 50, 0, 0, 0, 0, 0, 0
.hword 755, 50, 0, 0, 0, 0, 0, 0
.hword 756, 50, 0, 0, 0, 0, 0, 0
.hword 757, 50, 0, 0, 0, 0, 0, 0
.hword 758, 50, 0, 0, 0, 0, 0, 0
.hword 759, 50, 0, 0, 0, 0, 0, 0
.hword 760, 50, 0, 0, 0, 0, 0, 0
.hword 761, 50, 0, 0, 0, 0, 0, 0
.hword 762, 50, 0, 0, 0, 0, 0, 0
.hword 763, 50, 0, 0, 0, 0, 0, 0
.hword 764, 50, 0, 0, 0, 0, 0, 0
.hword 765, 50, 0, 0, 0, 0, 0, 0
.hword 766, 50, 0, 0, 0, 0, 0, 0
.hword 767, 50, 0, 0, 0, 0, 0, 0
.hword 768, 50, 0, 0, 0, 0, 0, 0
.hword 769, 50, 0, 0, 0, 0, 0, 0
.hword 770, 50, 0, 0, 0, 0, 0, 0
.hword 771, 50, 0, 0, 0, 0, 0, 0
.hword 772, 50, 0, 0, 0, 0, 0, 0
.hword 773, 50, 0, 0, 0, 0, 0, 0
.hword 774, 50, 0, 0, 0, 0, 0, 0
.hword 775, 50, 0, 0, 0, 0, 0, 0
.hword 776, 50, 0, 0, 0, 0, 0, 0
.hword 777, 50, 0, 0, 0, 0, 0, 0
.hword 778, 50, 0, 0, 0, 0, 0, 0
.hword 779, 50, 0, 0, 0, 0, 0, 0
.hword 780, 50, 0, 0, 0, 0, 0, 0
.hword 781, 50, 0, 0, 0, 0, 0, 0
.hword 782, 50, 0, 0, 0, 0, 0, 0
.hword 783, 50, 0, 0, 0, 0, 0, 0
.hword 784, 50, 0, 0, 0, 0, 0, 0
.hword 785, 50, 0, 0, 0, 0, 0, 0
.hword 786, 50, 0, 0, 0, 0, 0, 0
.hword 787, 50, 0, 0, 0, 0, 0, 0
.hword 788, 50, 0, 0, 0, 0, 0, 0
.hword 789, 50, 0, 0, 0, 0, 0, 0
.hword 790, 50, 0, 0, 0, 0, 0, 0
.hword 791, 50, 0, 0, 0, 0, 0, 0
.hword 792, 50, 0, 0, 0, 0, 0, 0
.hword 793, 50, 0, 0, 0, 0, 0, 0
.hword 794, 50, 0, 0, 0, 0, 0, 0
.hword 795, 50, 0, 0, 0, 0, 0, 0
.hword 796, 50, 0, 0, 0, 0, 0, 0
.hword 797, 50, 0, 0, 0, 0, 0, 0
.hword 798, 50, 0, 0, 0, 0, 0, 0
.hword 799, 50, 0, 0, 0, 0, 0, 0
.hword 800, 50, 0, 0, 0, 0, 0, 0

// palmer mons

.hword 801, 50, slowking, leftovers, calmmind, psyshock, scald, slackoff
.hword 802, 50, rhyperior, choiceband, rockwrecker, earthquake, thunderpunch, crunch
.hword 803, 50, dragonite, weaknesspolicy, outrage, thunderpunch, firepunch, extremespeed

.hword 804, 50, slowking, leftovers, trickroom, scald, flamethrower, icebeam
.hword 805, 50, rhyperior, assaultvest, hihorsepower, rockslide, thunderpunch, protect
.hword 806, 50, annihilape, sitrusberry, bulkup, drainpunch, ragefist, protect
.hword 807, 50, dragonite, weaknesspolicy, dragondance, firepunch, icepunch, thunderpunch

.hword 808, 50, irontreads, boosterenergy, earthquake, ironhead, knockoff, voltswitch
.hword 809, 50, moltresgalarian, weaknesspolicy, nastyplot, airslash, roost, fierywrath
.hword 810, 50, suicune, leftovers, calmmind, scald, icebeam, snarl

.hword 811, 50, irontreads, boosterenergy, earthquake, rockslide, ironhead, voltswitch
.hword 812, 50, moltresgalarian, weaknesspolicy, nastyplot, airslash, protect, fierywrath
.hword 813, 50, latios, souldew, protect, icebeam, psyshock, calmmind
.hword 814, 50, suicune, leftovers, scald, protect, snarl, tailwind



PokemonTableStartHardModeSpreads:
/* venusaur */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* venusaur */ .byte bold, 0, 0, 0, maxivs, 170, 0, 170, 0, 0, 170, pokeball, abilityone, 0, 0, 0
/* venusaur */ .byte lonely, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* venusaur */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* charizard */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* charizard */ .byte naive, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* charizard */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* charizard */ .byte naive, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* blastoise */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* blastoise */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* blastoise */ .byte bold, 0, 0, 0, maxivs, 170, 0, 170, 0, 0, 170, pokeball, abilityone, 0, 0, 0
/* blastoise */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* pidgeot */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* pidgeot */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* pidgeot */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* pidgeot */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* arbok */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* arbok */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* arbok */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* arbok */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* raichu */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* raichu */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* raichu */ .byte calm, 0, 0, 0, maxivs, 170, 0, 170, 0, 0, 170, pokeball, abilityone, 0, 0, 0
/* raichu */ .byte hasty, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* sandslash */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* sandslash */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* sandslash */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* sandslash */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* nidoqueen */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* nidoqueen */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* nidoqueen */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* nidoqueen */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* nidoking */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* nidoking */ .byte naive, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* nidoking */ .byte hasty, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* nidoking */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* clefable */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* clefable */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* clefable */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* clefable */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* ninetales */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* ninetales */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* ninetales */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* ninetales */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* wigglytuff */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* wigglytuff */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* wigglytuff */ .byte modest, 0, 0, 0, maxivs, 0, 0, 255, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* wigglytuff */ .byte modest, 0, 0, 0, maxivs, 0, 0, 255, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* vileplume */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* vileplume */ .byte modest, 0, 0, 0, maxivs, 0, 0, 255, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* vileplume */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* vileplume */ .byte calm, 0, 0, 0, maxivs, 255, 0, 0, 0, 0, 255, pokeball, abilitytwo, 0, 0, 0
/* parasect */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* parasect */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* parasect */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* parasect */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* venomoth */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* venomoth */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* venomoth */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* venomoth */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* dugtrio */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* dugtrio */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* dugtrio */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* dugtrio */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* persian */ .byte jolly, 0, 0, 0, maxivs, 255, 0, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* persian */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* persian */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* persian */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* golduck */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* golduck */ .byte serious, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* golduck */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* golduck */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* annihilape */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* annihilape */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* annihilape */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* annihilape */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* arcanine */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* arcanine */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* arcanine */ .byte serious, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* arcanine */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* poliwrath */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* poliwrath */ .byte careful, 0, 0, 0, maxivs, 255, 0, 0, 0, 0, 255, pokeball, abilityone, 0, 0, 0
/* poliwrath */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* poliwrath */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* alakazam */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* alakazam */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* alakazam */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* alakazam */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* machamp */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* machamp */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* machamp */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* machamp */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* victreebel */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* victreebel */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* victreebel */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* victreebel */ .byte serious, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* tentacruel */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* tentacruel */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* tantacruel */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* tentacruel */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* golem */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* golem */ .byte n, 0, 0, 0, maxivs, 0, 255, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* golem */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* golem */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* rapidash */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* rapidash */ .byte timid, 0, 0, 0, maxivs, 255, 0, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* rapidash */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* rapidash */ .byte timid, 0, 0, 0, maxivs, 255, 0, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* slowbro */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* slowbro */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* slowbro */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* slowbro */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* dodrio */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* dodrio */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* dodrio */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* dodrio */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* dewgong */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* dewgong */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* dewgong */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* dewgong */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* muk */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* muk */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* muk */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* muk */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* cloyster */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* cloyster */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* cloyster */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* cloyster */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* gengar */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* gengar */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* gengar */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* gengar */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* hypno */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* hypno */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* hypno */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* hypno */ .byte relaxed, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* kingler */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* kingler */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* kingler */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* kingler */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* electrode */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* electrode */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* electrode */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* electrode */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* exeggutor */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* exeggutor */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* exeggutor */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* exeggutor */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* marowak */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* marowak */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* marowak */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* marowak */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* hitmonlee */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* hitmonlee */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* hitmonlee */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* hitmonlee */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* hitmonchan */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* hitmonchan */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* hitmonchan */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* hitmonchan */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* weezing */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* weezing */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* weezing */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* weezing */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* kangaskhan */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* kangaskhan */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* kangaskhan */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* kangaskhan */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* seaking */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* seaking */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* seaking */ .byte careful, 0, 0, 0, maxivs, 255, 0, 0, 0, 0, 255, pokeball, abilitytwo, 0, 0, 0
/* seaking */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* starmie */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* starmie */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* starmie */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* starmie */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* jynx */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* jynx */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* jynx */ .byte modest, 0, 0, 0, maxivs, 0, 0, 255, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* jynx */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* pinsir */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* pinsir */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* pinsir */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* pinsir */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* tauros */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* tauros */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* tauros */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* tauros */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* gyarados */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* gyarados */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* gyarados */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* gyarados */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* lapras */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* lapras */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* lapras */ .byte calm, 0, 0, 0, maxivs, 255, 0, 0, 0, 0, 255, pokeball, abilityone, 0, 0, 0
/* lapras */ .byte quiet, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* ditto */ .byte serious, 0, 0, 0, maxivs, 255, 0, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* ditto */ .byte serious, 0, 0, 0, maxivs, 255, 0, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* ditto */ .byte serious, 0, 0, 0, maxivs, 255, 0, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* ditto */ .byte serious, 0, 0, 0, maxivs, 255, 0, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* vaporeon */ .byte bold, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* vaporeon */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* vaporeon */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* vaporeon */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* jolteon */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* jolteon */ .byte modest, 0, 0, 0, ice, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* jolteon */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* jolteon */ .byte modest, 0, 0, 0, ice, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* flareon */ .byte hasty, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* flareon */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* flareon */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* flareon */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* omaster */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* omaster */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* omaster */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* omaster */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* kabutops */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* kabutops */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* kabutops */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* kabutops */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* aerodactyl */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* aerodactyl */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* aerodactyl */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* aerodactyl */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* snorlax */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* snorlax */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* snorlax */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* snorlax */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* articuno */ .byte calm, 0, 0, 0, maxivs, 255, 0, 0, 0, 0, 255, pokeball, abilityone, 0, 0, 0
/* articuno */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* zapdos */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* zapdos */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* moltres */ .byte relaxed, 0, 0, 0, maxivs, 170, 0, 170, 0, 0, 170, pokeball, abilityone, 0, 0, 0
/* moltres */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* dragonite */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* dragonite */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* dragonite */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* dragonite */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* meganium */ .byte serious, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* meganium */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* meganium */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* meganium */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* typhlosion */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* typhlosion */ .byte hasty, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* typhlosion */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* typhlosion */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* feraligatr */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* feraligatr */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* feraligatr */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* feraligatr */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* crobat */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* crobat */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* crobat */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* crobat */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* lanturn */ .byte calm, 0, 0, 0, maxivs, 255, 0, 0, 0, 0, 255, pokeball, abilityone, 0, 0, 0
/* lanturn */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* lanturn */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* lanturn */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* xatu */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* xatu */ .byte calm, 0, 0, 0, maxivs, 255, 0, 0, 0, 0, 255, pokeball, abilitytwo, 0, 0, 0
/* xatu */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* xatu */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* ampharos */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* ampharos */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* ampharos */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* ampharos */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* bellossom */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* bellossom */ .byte modest, 0, 0, 0, fire, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* bellossom */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* bellossom */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* azumarill */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* azumarill */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* azumarill */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* azumarill */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* sudowoodo */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* sudowoodo */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* sudowoodo */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* sudowoodo */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* politoed */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* politoed */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* politoed */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* politoed */ .byte calm, 0, 0, 0, maxivs, 255, 0, 0, 0, 0, 255, pokeball, abilitytwo, 0, 0, 0
/* jumpluff */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* jumpluff */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* jumpluff */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* jumpluff */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* sunflora */ .byte modest, 0, 0, 0, fire, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* sunflora */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* sunflora */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* sunflora */ .byte modest, 0, 0, 0, fire, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* quagsire */ .byte relaxed, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* quagsire */ .byte brave, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* quagsire */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* quagsire */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* espeon */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* espeon */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* espeon */ .byte timid, 0, 0, 0, fire, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* espeon */ .byte calm, 0, 0, 0, maxivs, 255, 0, 0, 0, 0, 255, pokeball, abilitytwo, 0, 0, 0
/* umbreon */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* umbreon */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* umbreon */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* umbreon */ .byte careful, 0, 0, 0, maxivs, 255, 0, 0, 0, 0, 255, pokeball, abilityone, 0, 0, 0
/* slowking */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* slowking */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* slowking */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* slowking */ .byte calm, 0, 0, 0, maxivs, 255, 0, 0, 0, 0, 255, pokeball, abilitytwo, 0, 0, 0
/* forretress */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* forretress */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* forretress */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* forretress */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* steelix */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* steelix */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* steelix */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* steelix */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* granbull */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* granbull */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* granbull */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* granbull */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* scizor */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* scizor */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* scizor */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* scizor */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* shuckle */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* shuckle */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* shuckle */ .byte calm, 0, 0, 0, maxivs, 255, 0, 0, 0, 0, 255, pokeball, abilityone, 0, 0, 0
/* shuckle */ .byte careful, 0, 0, 0, maxivs, 255, 0, 0, 0, 0, 255, pokeball, abilityone, 0, 0, 0
/* heracross */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* heracross */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* heracross */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* heracross */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* magcargo */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* magcargo */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* magcargo */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* magcargo */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* octillery */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* octillery */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* octillery */ .byte calm, 0, 0, 0, maxivs, 255, 0, 0, 0, 0, 255, pokeball, abilityone, 0, 0, 0
/* octillery */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* mantine */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* mantine */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* mantine */ .byte calm, 0, 0, 0, maxivs, 255, 0, 0, 0, 0, 255, pokeball, abilitytwo, 0, 0, 0
/* mantine */ .byte calm, 0, 0, 0, maxivs, 255, 0, 0, 0, 0, 255, pokeball, abilitytwo, 0, 0, 0
/* skarmory */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* skarmory */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* skarmory */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* skarmory */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* houndoom */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* houndoom */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* houndoom */ .byte bold, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* houndoom */ .byte jolly, 0, 0, 0, maxivs, 255, 0, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* kingdra */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* kingdra */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* kingdra */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* kingdra */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* donphan */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* donphan */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* donphan */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* donphan */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* smeargle */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* smeargle */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* smeargle */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* smeargle */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* hitmontop */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* hitmontop */ .byte careful, 0, 0, 0, maxivs, 255, 0, 0, 0, 0, 255, pokeball, abilitytwo, 0, 0, 0
/* hitmontop */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* hitmontop */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* miltank */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* miltank */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* miltank */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* miltank */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* blissey */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* blissey */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* blissey */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* blissey */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* raikou */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* raikou */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* entei */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* entei */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* suicune */ .byte calm, 0, 0, 0, maxivs, 255, 0, 0, 0, 0, 255, pokeball, abilityone, 0, 0, 0
/* suicune */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* tyranitar */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* tyranitar */ .byte naive, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* tyranitar */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* tyranitar */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* leafeon */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* leafeon */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* leafeon */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* leafeon */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* glaceon */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* glaceon */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* glaceon */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* glaceon */ .byte calm, 0, 0, 0, maxivs, 255, 0, 0, 0, 0, 255, pokeball, abilityone, 0, 0, 0
/* sylveon */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* sylveon */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* sylveon */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* sylveon */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* honchkrow */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* honchkrow */ .byte hasty, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* honchkrow */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* honchkrow */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* mismagius */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* mismagius */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* mismagius */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* mismagius */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* gliscor */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* gliscor */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* gliscor */ .byte jolly, 0, 0, 0, maxivs, 255, 0, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* gliscor */ .byte careful, 0, 0, 0, maxivs, 255, 0, 0, 0, 0, 255, pokeball, abilitytwo, 0, 0, 0
/* weavile */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* weavile */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* weavile */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* weavile */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* togekiss */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* togekiss */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* togekiss */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* togekiss */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* magnezone */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* magnezone */ .byte modest, 0, 0, 0, fire, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* magnezone */ .byte modest, 0, 0, 0, maxivs, 0, 0, 255, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* magnezone */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* magmortar */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* magmortar */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* magmortar */ .byte modest, 0, 0, 0, maxivs, 0, 0, 255, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* magmortar */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* electivire */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* electivire */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* electivire */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* electivire */ .byte n, 0, 0, 0, maxivs, 0, 0, 255, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* rhyperior */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 0, 0, 255, pokeball, abilitytwo, 0, 0, 0
/* rhyperior */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* rhyperior */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* rhyperior */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* raichualolan */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* raichualolan */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* sandslashalolan */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* sandslashalolan */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* ninetalesalolan */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* ninetalesalolan */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* dugtrioalolan */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* dugtrioalolan */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* persianalolan */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* persianalolan */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* golemalolan */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* golemalolan */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* mukalolan */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* mukalolan */ .byte careful, 0, 0, 0, maxivs, 255, 0, 0, 0, 0, 255, pokeball, abilityone, 0, 0, 0
/* exeggutoralolan */ .byte brave, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* exeggutoralolan */ .byte brave, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* marowakalolan */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* marowakalolan */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* rapidashgalarian */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* rapidashgalarian */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* slowbrogalarian */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* slowbrogalarian */ .byte relaxed, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* slowkinggalarian */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* slowkinggalarian */ .byte quiet, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* sirfetchd */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* sirfetchd */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* sirfetchd */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* sirfetchd */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* weezinggalarian */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* weezinggalarian */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* mrrime */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* mrrime */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* mrrime */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* mrrime */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* articunogalarian */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* articunogalarian */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* zapdosgalarian */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* zapdosgalarian */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* moltresgalarian */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* moltresgalarian */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* cursola */ .byte modest, 0, 0, 0, maxivs, 0, 0, 255, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* cursola */ .byte modest, 0, 0, 0, maxivs, 0, 0, 255, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* cursola */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* cursola */ .byte modest, 0, 0, 0, maxivs, 0, 0, 255, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* arcaninehisuian */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* arcaninehisuian */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* electrodehisuian */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* electrodehisuian */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* kleavor */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* kleavor */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* kleavor */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* kleavor */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* typhlosionhisuian */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* typhlosionhisuian */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* overqwil */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* overqwil */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* overqwil */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* overqwil */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* sneasler */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* sneasler */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* sneasler */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* sneasler */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* ursaluna */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* ursaluna */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* ursaluna */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* ursaluna */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* wyrdeer */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* wyrdeer */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* wyrdeer */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* wyrdeer */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* porygonz */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* porygonz */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* porygonz */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* porygonz */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* yanmega */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* yanmega */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* yanmega */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* yanmega */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* mamoswine */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* mamoswine */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* mamoswine */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* mamoswine */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* ambipom */ .byte n, 0, 0, 0, maxivs, 0, 0, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* ambipom */ .byte n, 0, 0, 0, maxivs, 0, 0, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* ambipom */ .byte n, 0, 0, 0, maxivs, 0, 0, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* ambipom */ .byte n, 0, 0, 0, maxivs, 0, 0, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* lickilicky */ .byte brave, 0, 0, 0, maxivs, 0, 255, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* lickilicky */ .byte careful, 0, 0, 0, maxivs, 255, 0, 0, 0, 0, 255, pokeball, abilitytwo, 0, 0, 0
/* lickilicky */ .byte quiet, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* lickilicky */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* tangrowth */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* tangrowth */ .byte relaxed, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* tangrowth */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* tangrowth */ .byte quiet, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* perrserker */ .byte adamant, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* perrserker */ .byte adamant, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* perrserker */ .byte adamant, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* perrserker */ .byte adamant, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0

/* tauroscombat */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* tauroscombat */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* taurosblaze  */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* taurosblaze  */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* taurosaqua   */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* taurosaqua   */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* wugtrio      */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* wugtrio      */ .byte hasty, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* toedscruel   */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* toedscruel   */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* clodsire     */ .byte careful, 0, 0, 0, maxivs, 255, 0, 0, 0, 0, 255, pokeball, abilitytwo, 0, 0, 0
/* clodsire     */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* dudunsparce  */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* dudunsparce  */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* dudunsparce  */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* dudunsparce  */ .byte sassy, 0, 0, 0, maxivs, 255, 0, 0, 0, 0, 255, pokeball, abilityone, 0, 0, 0
/* farigiraf    */ .byte quiet, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* farigiraf    */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* farigiraf    */ .byte quiet, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* farigiraf    */ .byte quiet, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
/* screamtail   */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
/* screamtail   */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* fluttermane  */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* fluttermane  */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* sandyshocks  */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* sandyshocks  */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* greattusk    */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* greattusk    */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* irontreads   */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* irontreads   */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* ironbundle   */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* ironbundle   */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* ironthorns   */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* ironthorns   */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
/* walkingwake  */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
/* walkingwake  */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0

/* 567 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 568 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 569 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 570 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 571 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 572 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 573 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 574 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 575 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 576 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 577 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 578 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 579 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 580 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 581 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 582 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 583 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 584 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 585 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 586 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 587 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 588 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 589 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 590 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 591 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 592 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 593 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 594 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 595 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 596 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 597 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 598 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 599 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 600 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 601 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 602 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 603 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 604 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 605 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 606 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 607 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 608 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 609 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 610 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 611 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 612 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 613 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 614 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 615 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 616 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 617 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 618 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 619 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 620 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 621 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 622 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 623 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 624 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 625 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 626 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 627 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 628 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 629 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 630 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 631 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 632 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 633 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 634 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 635 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 636 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 637 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 638 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 639 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 640 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 641 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 642 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 643 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 644 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 645 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 646 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 647 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 648 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 649 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 650 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 651 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 652 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 653 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 654 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 655 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 656 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 657 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 658 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 659 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 660 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 661 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 662 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 663 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 664 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 665 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 666 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 667 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 668 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 669 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 670 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 671 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 672 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 673 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 674 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 675 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 676 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 677 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 678 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 679 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 680 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 681 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 682 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 683 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 684 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 685 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 686 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 687 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 688 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 689 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 690 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 691 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 692 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 693 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 694 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 695 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 696 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 697 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 698 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 699 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 700 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 701 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 702 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 703 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 704 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 705 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 706 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 707 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 708 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 709 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 710 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 711 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 712 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 713 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 714 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 715 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 716 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 717 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 718 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 719 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 720 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 721 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 722 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 723 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 724 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 725 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 726 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 727 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 728 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 729 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 730 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 731 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 732 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 733 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 734 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 735 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 736 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 737 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 738 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 739 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 740 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 741 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 742 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 743 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 744 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 745 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 746 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 747 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 748 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 749 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 750 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 751 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 752 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 753 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 754 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 755 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 756 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 757 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 758 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 759 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 760 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 761 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 762 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 763 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 764 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 765 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 766 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 767 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 768 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 769 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 770 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 771 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 772 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 773 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 774 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 775 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 776 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 777 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 778 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 779 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 780 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 781 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 782 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 783 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 784 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 785 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 786 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 787 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 788 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 789 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 790 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 791 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 792 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 793 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 794 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 795 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 796 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 797 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 798 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 799 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0
/* 800 */ .byte 0, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilitytwo, 0, 0, 0

// palmer mon spreads should be good on this too

/* slowking */ .byte modest, 0, 0, 0, maxivs, 248, 0, 92, 0, 168, 0, pokeball, abilitytwo, 0, 0, 0
/* rhyperior */ .byte adamant, 0, 0, 0, maxivs, 4, 252, 0, 252, 0, 0, pokeball, abilitytwo, 0, 0, 0
/* dragonite */ .byte jolly, 0, 0, 0, maxivs, 4, 252, 0, 252, 0, 0, pokeball, abilitytwo, 0, 0, 0

/* slowking */ .byte quiet, 0, 0, 0, maxivs, 212, 0, 0, 0, 252, 44, pokeball, abilitytwo, 0, 0, 0
/* rhyperior */ .byte adamant, 0, 0, 0, maxivs, 252, 16, 0, 0, 0, 240, pokeball, abilityone, 0, 0, 0
/* annihilape */ .byte adamant, 0, 0, 0, maxivs, 252, 196, 12, 20, 0, 28, pokeball, abilityone, 0, 0, 0
/* dragonite */ .byte jolly, 0, 0, 0, maxivs, 0, 252, 0, 252, 0, 4, pokeball, abilitytwo, 0, 0, 0

/* irontreads */ .byte jolly, 0, 0, 0, maxivs, 0, 252, 0, 252, 0, 4, pokeball, abilityone, 0, 0, 0
/* galarianmoltres */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 252, 252, 4, pokeball, abilityone, 0, 0, 0
/* suicune */ .byte calm, 0, 0, 0, maxivs, 252, 0, 40, 0, 0, 216, pokeball, abilityone, 0, 0, 0

/* irontreads */ .byte jolly, 0, 0, 0, maxivs, 0, 252, 0, 252, 0, 4, pokeball, abilityone, 0, 0, 0
/* galarianmoltres */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 252, 252, 4, pokeball, abilityone, 0, 0, 0
/* latios */ .byte timid, 0, 0, 0, maxivs, 0, 0, 4, 252, 252, 0, pokeball, abilityone, 0, 0, 0
/* suicune */ .byte bold, 0, 0, 0, maxivs, 252, 0, 40, 56, 52, 108, pokeball, abilityone, 0, 0, 0


.thumb
.thumb_func
.align 2
