.thumb
.thumb_func
.align 2

// included from "battle_tower_create_party.s"


// fire gold battle tower easy mode spreads

PokemonTableStartEasyMode:
    .hword  1, 50, bayleef, occaberry, magicalleaf, ancientpower, leechseed, lightscreen
    .hword  2, 50, quilava, passhoberry, lavaplume, rollout, smokescreen, willowisp
    .hword  3, 50, croconaw, rindoberry, dive, bite, icefang, scaryface
    .hword  4, 50, fearow, wacanberry, aerialace, facade, mudslap, leer
    .hword  5, 50, noctowl, sharpbeak, aircutter, psybeam, hypnosis, reflect
    .hword  6, 50, raticate, scopelens, hyperfang, bite, agility, focusenergy
    .hword  7, 50, furret, silkscarf, facade, coil, amnesia, batonpass
    .hword  8, 50, pikachu, lightball, shockwave, nuzzle, quickattack, brickbreak
    .hword  9, 50, butterfree, chartiberry, psybeam, silverwind, sleeppowder, quiverdance
    .hword 10, 50, beedrill, focussash, twineedle, swordsdance, endeavor, aerialace
    .hword 11, 50, ledian, lightclay, silverwind, drainpunch, lightscreen, reflect
    .hword 12, 50, ariados, blacksludge, toxicthread, crosspoison, stickyweb, psybeam
    .hword 13, 50, graveler, softsand, rocktomb, magnitude, defensecurl, rockpolish
    .hword 14, 50, golbat, wacanberry, crosspoison, aerialace, meanlook, confuseray
    .hword 15, 50, wigglytuff, chestoberry, disarmvoice, sing, swift, rest
    .hword 16, 50, togetic, sitrusberry, aerialace, magicalleaf, yawn, wish
    .hword 17, 50, sandslash, smoothrock, dig, sandstorm, rocktomb, rapidspin
    .hword 18, 50, arbok, payapaberry, poisontail, coil, bite, glare
    .hword 19, 50, dunsparce, chopleberry, glare, headbutt, bite, magiccoat
    .hword 20, 50, flaaffy, magnet, thunderwave, shockwave, cottonguard, eerieimpulse
    .hword 21, 50, quagsire, rindoberry, waterpulse, mudbomb, yawn, amnesia
    .hword 22, 50, haunter, kasibberry, ominouswind, confuseray, hypnosis, curse
    .hword 23, 50, onix, weaknesspolicy, dig, rocktomb, irondefense, dragonbreath
    .hword 24, 50, weepinbell, payapaberry, gigadrain, acid, stunspore, synthesis
    .hword 25, 50, parasect, leftovers, xscissor, bulletseed, spore, screech
    .hword 26, 50, poliwhirl, expertbelt, bubblebeam, brickbreak, hypnosis, mudshot
    .hword 27, 50, seaking, damprock, dive, psybeam, raindance, mist
    .hword 28, 50, gloom, blacksludge, gigadrain, acid, moonlight, toxic
    .hword 29, 50, hypno, twistedspoon, psychocut, hypnosis, nightmare, headbutt
    .hword 30, 50, kadabra, colburberry, psybeam, kinesis, barrier, shockwave
    .hword 31, 50, nidorina, muscleband, poisonfang, bite, doublekick, flatter
    .hword 32, 50, nidorino, wiseglasses, poisonfang, waterpulse, psybeam, flatter
    .hword 33, 50, yanma, brightpowder, uturn, aerialace, detect, doubleteam
    .hword 34, 50, sunflora, miracleseed, gigadrain, ingrain, leechseed, flowerguard
    .hword 35, 50, sudowoodo, hardstone, rocktomb, feintattack, lowkick, block
    .hword 36, 50, wobbuffet, sitrusberry, counter, mirrorcoat, encore, destinybond
    .hword 37, 50, venomoth, silverpowder, silverwind, psybeam, sleeppowder, skillswap
    .hword 38, 50, scyther, chartiberry, uturn, aerialace, lightscreen, leer
    .hword 39, 50, magneton, metalcoat, shockwave, mirrorshot, thunderwave, supersonic
    .hword 40, 50, aipom, silkscarf, fakeout, doublehit, thunderwave, thief
    .hword 41, 50, granbull, kebiaberry, facade, roar, thunderwave, bite
    .hword 42, 50, stantler, muscleband, psybeam, stomp, confuseray, sandattack
    .hword 43, 50, azumarill, persimberry, aquajet, facade, raindance, defensecurl
    .hword 44, 50, primeape, cobaberry, brickbreak, swagger, assurance, focusenergy
    .hword 45, 50, persian, focusband, slash, bite, torment, swagger
    .hword 46, 50, machoke, blackbelt, rocktomb, lowkick, scaryface, focusenergy
    .hword 47, 50, girafarig, tangaberry, psybeam, stomp, wish, skillswap
    .hword 48, 50, magmar, cheriberry, firepunch, barrier, feintattack, willowisp
    .hword 49, 50, jynx, babiriberry, lovelykiss, icywind, psybeam, faketears
    .hword 50, 50, electabuzz, rawstberry, thunderpunch, lightscreen, lowkick, thunderwave
    .hword 51, 50, mrmime, oranberry, barrier, psybeam, fakeout, magicalleaf
    .hword 52, 50, smeargle, lumberry, spore, bellydrum, shadowsneak, quickattack
    .hword 53, 50, farfetchd, stick, aerialace, slash, agility, swordsdance
    .hword 54, 50, qwilfish, poisonbarb, barbbarrage, waterpulse, pinmissile, minimize
    .hword 55, 50, shuckle, oranberry, wrap, toxic, protect, sandstorm
    .hword 56, 50, corsola, widelens, rockblast, bubblebeam, recover, bulldoze
    .hword 57, 50, octillery, expertbelt, octazooka, aurorabeam, psybeam, bulletseed
    .hword 58, 50, lickitung, ganlonberry, defensecurl, refresh, rollout, facade
    .hword 59, 50, tangela, occaberry, gigadrain, wrap, amnesia, leechseed
    .hword 60, 50, seadra, pechaberry, dragonbreath, octazooka, agility, smokescreen
    .hword 61, 50, gligar, yacheberry, bulldoze, acrobatics, swordsdance, toxic
    .hword 62, 50, delibird, icyrock, icywind, tailwind, aircutter, hail
    .hword 63, 50, piloswine, nevermeltice, iceshard, dig, mist, ancientpower
    .hword 64, 50, ursaring, persimberry, feintattack, scaryface, slash, charm
    .hword 65, 50, rhydon, aspearberry, bulldoze, rocktomb, scaryface, roar
    .hword 66, 50, murkrow, blackglasses, foulplay, taunt, swagger, suckerpunch
    .hword 67, 50, magcargo, shucaberry, ancientpower, flamewheel, shellsmash, acidarmor
    .hword 68, 50, misdreavus, spelltag, thunderwave, ominouswind, confuseray, painsplit
    .hword 69, 50, porygon2, chilanberry, psybeam, icywind, recycle, agility
    .hword 70, 50, chansey, sitrusberry, swift, refresh, defensecurl, minimize
    .hword 71, 50, ivysaur, miracleseed, sludge, growth, synthesis, magicalleaf
    .hword 72, 50, charmeleon, charcoal, slash, firepunch, dragonbreath, aerialace
    .hword 73, 50, wartortle, mysticwater, waterpulse, bite, irondefense, yawn
    .hword 74, 50, dragonair, habanberry, dragonbreath, thunderwave, waterpulse, return
    .hword 75, 50, pupitar, pechaberry, dig, rocktomb, bite, scaryface

/* 
---------------------------------------------------------------------------------------
The format of each entry is:
.byte Nature, 0, 0, 0, HPType/IVs, HP, Atk, Def, Spd, SpA, SpD, Ball, Ability, 0, 0, 0

HPType: If given one of the 17 different Types, this will determine the Type of the
Move Hidden Power. If this is set to 0x1F, then it will set everything to 31 like it
would normally.
---------------------------------------------------------------------------------------
*/

PokemonTableStartEasyModeSpreads:
    /* bayleef    */ .byte docile, 0, 0, 0, maxivs, 170, 0, 170, 0, 170, 0, pokeball, abilityone, 0, 0, 0
    /* quilava    */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
    /* croconaw   */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
    /* fearow     */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
    /* noctowl    */ .byte bold, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
    /* raticate   */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
    /* furret     */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
    /* pikachu    */ .byte timid, 0, 0, 0, maxivs, 0, 170, 0, 170, 170, 0, pokeball, abilityone, 0, 0, 0
    /* butterfree */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
    /* beedrill   */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
    /* ledian     */ .byte serious, 0, 0, 0, maxivs, 170, 0, 170, 0, 0, 170, pokeball, abilityone, 0, 0, 0
    /* ariados    */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
    /* graveler   */ .byte impish, 0, 0, 0, maxivs, 0, 255, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
    /* golbat     */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
    /* wigglytuff */ .byte bold, 0, 0, 0, maxivs, 170, 0, 170, 0, 170, 0, pokeball, abilityone, 0, 0, 0
    /* togetic    */ .byte serious, 0, 0, 0, maxivs, 170, 0, 170, 0, 0, 170, pokeball, abilityone, 0, 0, 0
    /* sandslash  */ .byte adamant, 0, 0, 0, maxivs, 170, 170, 170, 0, 0, 0, pokeball, abilityone, 0, 0, 0
    /* arbok      */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
    /* dunsparce  */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
    /* flaaffy    */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
    /* quagsire   */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
    /* haunter    */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
    /* onix       */ .byte adamant, 0, 0, 0, maxivs, 0, 170, 170, 170, 0, 0, pokeball, abilityone, 0, 0, 0
    /* weepinbell */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
    /* parasect   */ .byte adamant, 0, 0, 0, maxivs, 170, 170, 170, 0, 0, 0, pokeball, abilityone, 0, 0, 0
    /* poliwhirl  */ .byte naive, 0, 0, 0, maxivs, 0, 170, 0, 170, 170, 0, pokeball, abilityone, 0, 0, 0
    /* seaking    */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
    /* gloom      */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
    /* hypno      */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
    /* kadabra    */ .byte timid, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
    /* nidorina   */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
    /* nidorino   */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
    /* yanma      */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
    /* sunflora   */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
    /* sudowoodo  */ .byte adamant, 0, 0, 0, maxivs, 170, 170, 170, 0, 0, 0, pokeball, abilityone, 0, 0, 0
    /* wobbuffet  */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
    /* venomoth   */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
    /* scyther    */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
    /* magneton   */ .byte modest, 0, 0, 0, maxivs, 0, 0, 255, 0, 255, 0, pokeball, abilityone, 0, 0, 0
    /* aipom      */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
    /* granbull   */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
    /* stantler   */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
    /* azumarill  */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
    /* primeape   */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
    /* persian    */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
    /* machoke    */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
    /* girafarig  */ .byte naive, 0, 0, 0, maxivs, 0, 170, 0, 170, 170, 0, pokeball, abilityone, 0, 0, 0
    /* magmar     */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
    /* jynx       */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
    /* electabuzz */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
    /* mrmime     */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 170, 170, 170, pokeball, abilityone, 0, 0, 0
    /* smeargle   */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
    /* farfetchd  */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
    /* qwilfish   */ .byte adamant, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
    /* shuckle    */ .byte bold, 0, 0, 0, maxivs, 0, 0, 255, 0, 0, 255, pokeball, abilityone, 0, 0, 0
    /* corsola    */ .byte brave, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
    /* octillery  */ .byte quiet, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
    /* lickitung  */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
    /* tangela    */ .byte modest, 0, 0, 0, maxivs, 0, 0, 255, 0, 255, 0, pokeball, abilityone, 0, 0, 0
    /* seadra     */ .byte modest, 0, 0, 0, maxivs, 0, 0, 170, 170, 170, 0, pokeball, abilityone, 0, 0, 0
    /* gligar     */ .byte adamant, 0, 0, 0, maxivs, 170, 170, 170, 0, 0, 0, pokeball, abilityone, 0, 0, 0
    /* delibird   */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
    /* piloswine  */ .byte adamant, 0, 0, 0, maxivs, 255, 255, 0, 0, 0, 0, pokeball, abilityone, 0, 0, 0
    /* ursaring   */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
    /* rhydon     */ .byte impish, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
    /* murkrow    */ .byte adamant, 0, 0, 0, maxivs, 170, 170, 170, 0, 0, 0, pokeball, abilityone, 0, 0, 0
    /* magcargo   */ .byte naive, 0, 0, 0, maxivs, 255, 0, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
    /* misdreavus */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 170, 170, 170, pokeball, abilityone, 0, 0, 0
    /* porygon2   */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
    /* chansey    */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
    /* ivysaur    */ .byte modest, 0, 0, 0, maxivs, 255, 0, 0, 0, 255, 0, pokeball, abilityone, 0, 0, 0
    /* charmeleon */ .byte jolly, 0, 0, 0, maxivs, 0, 255, 0, 255, 0, 0, pokeball, abilityone, 0, 0, 0
    /* wartortle  */ .byte bold, 0, 0, 0, maxivs, 255, 0, 255, 0, 0, 0, pokeball, abilityone, 0, 0, 0
    /* dragonair  */ .byte modest, 0, 0, 0, maxivs, 0, 0, 0, 255, 255, 0, pokeball, abilityone, 0, 0, 0
    /* pupitar    */ .byte adamant, 0, 0, 0, maxivs, 170, 170, 170, 0, 0, 0, pokeball, abilityone, 0, 0, 0
